package com.model.bill.dto;
// Generated Jun 11, 2012 10:40:10 AM by Hibernate Tools 3.2.1.GA

import com.model.therapybill.dto.Therapybill;
import com.model.visit.dto.Visit;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "bill", schema = "public")
@SequenceGenerator(name = "bill_seq", sequenceName = "bill_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)

public class Bill implements java.io.Serializable {

    private long id;
    private Visit visit;
    private BigDecimal consultationcharges;
    private Date createddate;
    private String therapyname;
    private BigDecimal therapycharge;
    private String investigationname;
    private BigDecimal investigationcharge;
    private BigDecimal totalbill;
    private Set<Therapybill> therapybills = new HashSet<Therapybill>(0);

    /**
     *
     */
    public Bill() {
    }

    /**
     *
     * @return
     */
    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(generator = "bill_seq")
    public long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "visitid", nullable = false)
    public Visit getVisit() {
        return this.visit;
    }

    /**
     *
     * @param visit
     */
    public void setVisit(Visit visit) {
        this.visit = visit;
    }

    /**
     *
     * @return
     */
    @Column(name = "consultationcharges", nullable = false, precision = 20)
    public BigDecimal getConsultationcharges() {
        return this.consultationcharges;
    }

    /**
     *
     * @param consultationcharges
     */
    public void setConsultationcharges(BigDecimal consultationcharges) {
        this.consultationcharges = consultationcharges;
    }

    /**
     * @return the createddate
     */
    @Temporal(javax.persistence.TemporalType.DATE)
    @Column(name = "createddate", nullable = false, length = 29)
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * @param createddate the createddate to set
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    @Column(name="therapyname", length=150)
    public String getTherapyname() {
        return this.therapyname;
    }

    public void setTherapyname(String therapyname) {
        this.therapyname = therapyname;
    }

    @Column(name="therapycharge", precision=10)
    public BigDecimal getTherapycharge() {
        return this.therapycharge;
    }

    public void setTherapycharge(BigDecimal therapycharge) {
        this.therapycharge = therapycharge;
    }

    @Column(name="investigationname", length=150)
    public String getInvestigationname() {
        return this.investigationname;
    }

    public void setInvestigationname(String investigationname) {
        this.investigationname = investigationname;
    }

    @Column(name="investigationcharge", precision=10)
    public BigDecimal getInvestigationcharge() {
        return this.investigationcharge;
    }

    public void setInvestigationcharge(BigDecimal investigationcharge) {
        this.investigationcharge = investigationcharge;
    }

    @Column(name="totalbill", precision=10)
    public BigDecimal getTotalbill() {
        return this.totalbill;
    }

    public void setTotalbill(BigDecimal totalbill) {
        this.totalbill = totalbill;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="bill")
    public Set<Therapybill> getTherapybills() {
        return this.therapybills;
    }

    public void setTherapybills(Set<Therapybill> therapybills) {
        this.therapybills = therapybills;
    }
}


