package com.model.operationBill.dto;
// Generated 10 Sep, 2017 4:37:34 PM by Hibernate Tools 3.2.1.GA


import com.model.detailsOperationBill.dto.Detailsoperationbillchild;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Operationbillchild generated by hbm2java
 */
@Entity
@Table(name="operationbillchild"
    ,schema="public"
)
        @SequenceGenerator(name = "operationbillchild_seq", sequenceName = "operationbillchild_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Operationbillchild  implements java.io.Serializable {


     private long operationbillidchild;
     private Operationbill operationbill;
     private Date operationbilldatechild;
     private BigDecimal operationbillchargeschild;
     private String operationbillremarkschild;
     private BigDecimal advancechild;
     private BigDecimal topaychild;
     private Long discountparcentagechild;
     private BigDecimal discountamountchild;
     private BigDecimal totalpayablechild;
     private BigDecimal receivedamountchild;
     private BigDecimal totalduechild;
     private Set<Detailsoperationbillchild> detailsoperationbillchilds = new HashSet<Detailsoperationbillchild>(0);

    public Operationbillchild() {
    }


    public Operationbillchild(long operationbillidchild, Operationbill operationbill, Date operationbilldatechild) {
        this.operationbillidchild = operationbillidchild;
        this.operationbill = operationbill;
        this.operationbilldatechild = operationbilldatechild;
    }
    public Operationbillchild(long operationbillidchild, Operationbill operationbill, Date operationbilldatechild, BigDecimal operationbillchargeschild, String operationbillremarkschild, BigDecimal advancechild, BigDecimal topaychild, Long discountparcentagechild, BigDecimal discountamountchild, BigDecimal totalpayablechild, BigDecimal receivedamountchild, BigDecimal totalduechild, Set<Detailsoperationbillchild> detailsoperationbillchilds) {
       this.operationbillidchild = operationbillidchild;
       this.operationbill = operationbill;
       this.operationbilldatechild = operationbilldatechild;
       this.operationbillchargeschild = operationbillchargeschild;
       this.operationbillremarkschild = operationbillremarkschild;
       this.advancechild = advancechild;
       this.topaychild = topaychild;
       this.discountparcentagechild = discountparcentagechild;
       this.discountamountchild = discountamountchild;
       this.totalpayablechild = totalpayablechild;
       this.receivedamountchild = receivedamountchild;
       this.totalduechild = totalduechild;
       this.detailsoperationbillchilds = detailsoperationbillchilds;
    }

     @Id

    @Column(name="operationbillidchild", unique=true, nullable=false)
     @GeneratedValue(generator = "operationbillchild_seq")
    public long getOperationbillidchild() {
        return this.operationbillidchild;
    }

    public void setOperationbillidchild(long operationbillidchild) {
        this.operationbillidchild = operationbillidchild;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="operationbillid", nullable=false)
    public Operationbill getOperationbill() {
        return this.operationbill;
    }

    public void setOperationbill(Operationbill operationbill) {
        this.operationbill = operationbill;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="operationbilldatechild", nullable=false, length=13)
    public Date getOperationbilldatechild() {
        return this.operationbilldatechild;
    }

    public void setOperationbilldatechild(Date operationbilldatechild) {
        this.operationbilldatechild = operationbilldatechild;
    }

    @Column(name="operationbillchargeschild", precision=20)
    public BigDecimal getOperationbillchargeschild() {
        return this.operationbillchargeschild;
    }

    public void setOperationbillchargeschild(BigDecimal operationbillchargeschild) {
        this.operationbillchargeschild = operationbillchargeschild;
    }

    @Column(name="operationbillremarkschild", length=2000)
    public String getOperationbillremarkschild() {
        return this.operationbillremarkschild;
    }

    public void setOperationbillremarkschild(String operationbillremarkschild) {
        this.operationbillremarkschild = operationbillremarkschild;
    }

    @Column(name="advancechild", precision=20)
    public BigDecimal getAdvancechild() {
        return this.advancechild;
    }

    public void setAdvancechild(BigDecimal advancechild) {
        this.advancechild = advancechild;
    }

    @Column(name="topaychild", precision=20)
    public BigDecimal getTopaychild() {
        return this.topaychild;
    }

    public void setTopaychild(BigDecimal topaychild) {
        this.topaychild = topaychild;
    }

    @Column(name="discountparcentagechild")
    public Long getDiscountparcentagechild() {
        return this.discountparcentagechild;
    }

    public void setDiscountparcentagechild(Long discountparcentagechild) {
        this.discountparcentagechild = discountparcentagechild;
    }

    @Column(name="discountamountchild", precision=20)
    public BigDecimal getDiscountamountchild() {
        return this.discountamountchild;
    }

    public void setDiscountamountchild(BigDecimal discountamountchild) {
        this.discountamountchild = discountamountchild;
    }

    @Column(name="totalpayablechild", precision=20)
    public BigDecimal getTotalpayablechild() {
        return this.totalpayablechild;
    }

    public void setTotalpayablechild(BigDecimal totalpayablechild) {
        this.totalpayablechild = totalpayablechild;
    }

    @Column(name="receivedamountchild", precision=20)
    public BigDecimal getReceivedamountchild() {
        return this.receivedamountchild;
    }

    public void setReceivedamountchild(BigDecimal receivedamountchild) {
        this.receivedamountchild = receivedamountchild;
    }

    @Column(name="totalduechild", precision=20)
    public BigDecimal getTotalduechild() {
        return this.totalduechild;
    }

    public void setTotalduechild(BigDecimal totalduechild) {
        this.totalduechild = totalduechild;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="operationbillchild")
    public Set<Detailsoperationbillchild> getDetailsoperationbillchilds() {
        return this.detailsoperationbillchilds;
    }

    public void setDetailsoperationbillchilds(Set<Detailsoperationbillchild> detailsoperationbillchilds) {
        this.detailsoperationbillchilds = detailsoperationbillchilds;
    }




}

