package com.model.operationBill.dto;
// Generated 10 Sep, 2017 4:37:34 PM by Hibernate Tools 3.2.1.GA



import com.model.detailsOperationBill.dto.Detailsoperationbill;
import com.model.doctorProcess.dto.Doctorinfo;
import com.model.operationType.dto.Operationtype;
import com.model.patient.dto.Patient;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Operationbill generated by hbm2java
 */
@Entity
@Table(name="operationbill"
    ,schema="public"
)
        @SequenceGenerator(name = "operationbill_seq", sequenceName = "operationbill_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Operationbill  implements java.io.Serializable {


     private long operationbillid;
     private Patient patient;
     private Doctorinfo doctorinfo;
     private Operationtype operationtype;
     private Date operationbilldate;
     private BigDecimal operationbillcharges;
     private String operationbillremarks;
     private BigDecimal advance;
     private BigDecimal topay;
     private Long discountparcentage;
     private BigDecimal discountamount;
     private BigDecimal totalpayable;
     private BigDecimal receivedamount;
     private BigDecimal totaldue;
     private Set<Operationbillchild> operationbillchilds = new HashSet<Operationbillchild>(0);
     private Set<Detailsoperationbill> detailsoperationbills = new HashSet<Detailsoperationbill>(0);

    public Operationbill() {
    }

	
    public Operationbill(long operationbillid, Date operationbilldate) {
        this.operationbillid = operationbillid;
        this.operationbilldate = operationbilldate;
    }
    public Operationbill(long operationbillid, Patient patient, Doctorinfo doctorinfo, Operationtype operationtype, Date operationbilldate, BigDecimal operationbillcharges, String operationbillremarks, BigDecimal advance, BigDecimal topay, Long discountparcentage, BigDecimal discountamount, BigDecimal totalpayable, BigDecimal receivedamount, BigDecimal totaldue, Set<Operationbillchild> operationbillchilds) {
       this.operationbillid = operationbillid;
       this.patient = patient;
       this.doctorinfo = doctorinfo;
       this.operationtype = operationtype;
       this.operationbilldate = operationbilldate;
       this.operationbillcharges = operationbillcharges;
       this.operationbillremarks = operationbillremarks;
       this.advance = advance;
       this.topay = topay;
       this.discountparcentage = discountparcentage;
       this.discountamount = discountamount;
       this.totalpayable = totalpayable;
       this.receivedamount = receivedamount;
       this.totaldue = totaldue;
       this.operationbillchilds = operationbillchilds;
    }

    public Operationbill(long operationbillid, Patient patient, Doctorinfo doctorinfo, Operationtype operationtype, Date operationbilldate, BigDecimal operationbillcharges, String operationbillremarks, BigDecimal advance,  Long discountparcentage, BigDecimal discountamount, BigDecimal totalpayable, BigDecimal receivedamount, BigDecimal totaldue, Set<Detailsoperationbill> detailsoperationbills) {
       this.operationbillid = operationbillid;
       this.patient = patient;
       this.doctorinfo = doctorinfo;
       this.operationtype = operationtype;
       this.operationbilldate = operationbilldate;
       this.operationbillcharges = operationbillcharges;
       this.operationbillremarks = operationbillremarks;
       this.advance = advance;
       this.discountparcentage = discountparcentage;
       this.discountamount = discountamount;
       this.totalpayable = totalpayable;
       this.receivedamount = receivedamount;
       this.totaldue = totaldue;
       this.detailsoperationbills = detailsoperationbills;
    }
   
     @Id 
    
    @Column(name="operationbillid", unique=true, nullable=false)
     @GeneratedValue(generator = "operationbill_seq")
    public long getOperationbillid() {
        return this.operationbillid;
    }
    
    public void setOperationbillid(long operationbillid) {
        this.operationbillid = operationbillid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patientid")
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doctorid")
    public Doctorinfo getDoctorinfo() {
        return this.doctorinfo;
    }
    
    public void setDoctorinfo(Doctorinfo doctorinfo) {
        this.doctorinfo = doctorinfo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="operationtypeid")
    public Operationtype getOperationtype() {
        return this.operationtype;
    }
    
    public void setOperationtype(Operationtype operationtype) {
        this.operationtype = operationtype;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="operationbilldate", nullable=false, length=13)
    public Date getOperationbilldate() {
        return this.operationbilldate;
    }
    
    public void setOperationbilldate(Date operationbilldate) {
        this.operationbilldate = operationbilldate;
    }
    
    @Column(name="operationbillcharges", precision=20)
    public BigDecimal getOperationbillcharges() {
        return this.operationbillcharges;
    }
    
    public void setOperationbillcharges(BigDecimal operationbillcharges) {
        this.operationbillcharges = operationbillcharges;
    }
    
    @Column(name="operationbillremarks", length=2000)
    public String getOperationbillremarks() {
        return this.operationbillremarks;
    }
    
    public void setOperationbillremarks(String operationbillremarks) {
        this.operationbillremarks = operationbillremarks;
    }
    
    @Column(name="advance", precision=20)
    public BigDecimal getAdvance() {
        return this.advance;
    }
    
    public void setAdvance(BigDecimal advance) {
        this.advance = advance;
    }
    
    @Column(name="topay", precision=20)
    public BigDecimal getTopay() {
        return this.topay;
    }
    
    public void setTopay(BigDecimal topay) {
        this.topay = topay;
    }
    
    @Column(name="discountparcentage")
    public Long getDiscountparcentage() {
        return this.discountparcentage;
    }
    
    public void setDiscountparcentage(Long discountparcentage) {
        this.discountparcentage = discountparcentage;
    }
    
    @Column(name="discountamount", precision=20)
    public BigDecimal getDiscountamount() {
        return this.discountamount;
    }
    
    public void setDiscountamount(BigDecimal discountamount) {
        this.discountamount = discountamount;
    }
    
    @Column(name="totalpayable", precision=20)
    public BigDecimal getTotalpayable() {
        return this.totalpayable;
    }
    
    public void setTotalpayable(BigDecimal totalpayable) {
        this.totalpayable = totalpayable;
    }
    
    @Column(name="receivedamount", precision=20)
    public BigDecimal getReceivedamount() {
        return this.receivedamount;
    }
    
    public void setReceivedamount(BigDecimal receivedamount) {
        this.receivedamount = receivedamount;
    }
    
    @Column(name="totaldue", precision=20)
    public BigDecimal getTotaldue() {
        return this.totaldue;
    }
    
    public void setTotaldue(BigDecimal totaldue) {
        this.totaldue = totaldue;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="operationbill")
    public Set<Operationbillchild> getOperationbillchilds() {
        return this.operationbillchilds;
    }
    
    public void setOperationbillchilds(Set<Operationbillchild> operationbillchilds) {
        this.operationbillchilds = operationbillchilds;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="operationbill")
    public Set<Detailsoperationbill> getDetailsoperationbills() {
        return this.detailsoperationbills;
    }

    public void setDetailsoperationbills(Set<Detailsoperationbill> detailsoperationbills) {
        this.detailsoperationbills = detailsoperationbills;
    }




}


