package com.model.BuildingType.dto;
// Generated Jul 5, 2016 12:46:31 PM by Hibernate Tools 3.2.1.GA


import com.model.roomsetup.dto.Roomsetup;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * Buildingtypesetup generated by hbm2java
 */
@Entity
@Table(name="buildingtypesetup"
    ,schema="public"
)
         @SequenceGenerator(name = "buildingtype_seq", sequenceName = "buildingtype_seq")
         @org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Buildingtypesetup  implements java.io.Serializable {


     private long buildingid;
     private String buildingblock;
     private Long nooffloor;
     private Set<Roomsetup> roomsetups = new HashSet<Roomsetup>(0);

    public Buildingtypesetup() {
    }

	
    public Buildingtypesetup(long buildingid, String buildingblock) {
        this.buildingid = buildingid;
        this.buildingblock = buildingblock;
    }
    public Buildingtypesetup(long buildingid, String buildingblock, Long nooffloor) {
       this.buildingid = buildingid;
       this.buildingblock = buildingblock;
       this.nooffloor = nooffloor;
    }
    public Buildingtypesetup(long buildingid, String buildingblock, Long nooffloor, Set<Roomsetup> roomsetups) {
       this.buildingid = buildingid;
       this.buildingblock = buildingblock;
       this.nooffloor = nooffloor;
       this.roomsetups = roomsetups;
    }
   
     @Id 
    
    @Column(name="buildingid", unique=true, nullable=false)
      @GeneratedValue(generator = "buildingtype_seq")
    public long getBuildingid() {
        return this.buildingid;
    }
    
    public void setBuildingid(long buildingid) {
        this.buildingid = buildingid;
    }
    
    @Column(name="buildingblock", nullable=false)
    public String getBuildingblock() {
        return this.buildingblock;
    }
    
    public void setBuildingblock(String buildingblock) {
        this.buildingblock = buildingblock;
    }
    
    @Column(name="nooffloor")
    public Long getNooffloor() {
        return this.nooffloor;
    }
    
    public void setNooffloor(Long nooffloor) {
        this.nooffloor = nooffloor;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="buildingtypesetup")
    public Set<Roomsetup> getRoomsetups() {
        return this.roomsetups;
    }

    public void setRoomsetups(Set<Roomsetup> roomsetups) {
        this.roomsetups = roomsetups;
    }




}


