package com.model.investigationbill.dto;
// Generated Aug 8, 2014 12:06:45 PM by Hibernate Tools 3.2.1.GA


import com.model.detailInvestigationBill.dto.Detailsinvestigationbill;
import com.model.doctorProcess.dto.Doctorinfo;
import com.model.investigation.dto.Investigation;
import com.model.patient.dto.Patient;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Investigationbill generated by hbm2java
 */
@Entity
@Table(name="investigationbill"
    ,schema="public"
)
        @SequenceGenerator(name = "investigationbill_seq", sequenceName = "investigationbill_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Investigationbill  implements java.io.Serializable {


     private long investigationbillid;
     private Patient patient;
     private Doctorinfo doctorinfo;
     private Investigation investigation;
     private Date investigationbilldate;
     private BigDecimal investigationbillcharges;
     private String investigationbillremark;
     private BigDecimal advancedtaken;
     private Set<Detailsinvestigationbill> detailsinvestigationbills = new HashSet<Detailsinvestigationbill>(0);

    public Investigationbill() {
    }

	
    public Investigationbill(long investigationbillid, Investigation investigation, Date investigationbilldate, BigDecimal advancedtaken) {
        this.investigationbillid = investigationbillid;
        this.investigation = investigation;
        this.investigationbilldate = investigationbilldate;
        this.advancedtaken = advancedtaken;
    }
    public Investigationbill(long investigationbillid, Patient patient, Doctorinfo doctorinfo, Investigation investigation, Date investigationbilldate, BigDecimal investigationbillcharges, String investigationbillremark, Set<Detailsinvestigationbill> detailsinvestigationbills) {
       this.investigationbillid = investigationbillid;
       this.patient = patient;
       this.doctorinfo = doctorinfo;
       this.investigation = investigation;
       this.investigationbilldate = investigationbilldate;
       this.investigationbillcharges = investigationbillcharges;
       this.investigationbillremark = investigationbillremark;
       this.detailsinvestigationbills = detailsinvestigationbills;
    }
   
     @Id 
    
    @Column(name="investigationbillid", unique=true, nullable=false)
     @GeneratedValue(generator = "investigationbill_seq")
    public long getInvestigationbillid() {
        return this.investigationbillid;
    }
    
    public void setInvestigationbillid(long investigationbillid) {
        this.investigationbillid = investigationbillid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patientid")
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doctorid")
    public Doctorinfo getDoctorinfo() {
        return this.doctorinfo;
    }
    
    public void setDoctorinfo(Doctorinfo doctorinfo) {
        this.doctorinfo = doctorinfo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="investigationid", nullable=true)
    public Investigation getInvestigation() {
        return this.investigation;
    }
    
    public void setInvestigation(Investigation investigation) {
        this.investigation = investigation;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="investigationbilldate", nullable=false, length=13)
    public Date getInvestigationbilldate() {
        return this.investigationbilldate;
    }
    
    public void setInvestigationbilldate(Date investigationbilldate) {
        this.investigationbilldate = investigationbilldate;
    }
    
    @Column(name="investigationbillcharges", precision=20)
    public BigDecimal getInvestigationbillcharges() {
        return this.investigationbillcharges;
    }
    
    public void setInvestigationbillcharges(BigDecimal investigationbillcharges) {
        this.investigationbillcharges = investigationbillcharges;
    }
    
    @Column(name="investigationbillremark", length=2000)
    public String getInvestigationbillremark() {
        return this.investigationbillremark;
    }
    
    public void setInvestigationbillremark(String investigationbillremark) {
        this.investigationbillremark = investigationbillremark;
    }
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="investigationbill")
    public Set<Detailsinvestigationbill> getDetailsinvestigationbills() {
        return this.detailsinvestigationbills;
    }

    public void setDetailsinvestigationbills(Set<Detailsinvestigationbill> detailsinvestigationbills) {
        this.detailsinvestigationbills = detailsinvestigationbills;
    }

    @Column(name="advancedtaken", precision=20)
    public BigDecimal getAdvancedtaken() {
        return this.advancedtaken;
    }

    public void setAdvancedtaken(BigDecimal advancedtaken) {
        this.advancedtaken = advancedtaken;
    }





}


