package com.model.bbiochemistry.dto;
// Generated Jul 17, 2017 1:11:48 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bbiochemistry generated by hbm2java
 */
@Entity
@Table(name="bbiochemistry"
    ,schema="public"
)  @SequenceGenerator(name = "bbiochemistry_seq", sequenceName = "bbiochemistry_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Bbiochemistry  implements java.io.Serializable {


     private long id;
     private String name;
     private Short age;
     private String sex;
     private String referredby;
     private Long serialno;
     private String lipid;
     private String lipid1;
     private String lipid2;
     private String lipid3;
     private String lipid4;
     private String remarks;
     private String labtech;
     private String ddate;
      private Long opIpdno;

    public Bbiochemistry() {
    }

	
    public Bbiochemistry(long id) {
        this.id = id;
    }
    public Bbiochemistry(long id, String name, Short age, String sex, Long opIpdno, String referredby, Long serialno, String lipid, String lipid1, String lipid2, String lipid3, String lipid4, String remarks, String labtech, String ddate) {
       this.id = id;
       this.name = name;
       this.age = age;
       this.sex = sex;
       this.opIpdno = opIpdno;
       this.referredby = referredby;
       this.serialno = serialno;
       this.lipid = lipid;
       this.lipid1 = lipid1;
       this.lipid2 = lipid2;
       this.lipid3 = lipid3;
       this.lipid4 = lipid4;
       this.remarks = remarks;
       this.labtech = labtech;
       this.ddate = ddate;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
      @GeneratedValue(generator = "bbiochemistry_seq")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="name", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="age")
    public Short getAge() {
        return this.age;
    }
    
    public void setAge(Short age) {
        this.age = age;
    }
    
    @Column(name="sex", length=50)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
     @Column(name="op_ipdno")
    public Long getOpIpdno() {
        return this.opIpdno;
    }

    public void setOpIpdno(Long opIpdno) {
        this.opIpdno = opIpdno;
    }
    
    @Column(name="referredby", length=150)
    public String getReferredby() {
        return this.referredby;
    }
    
    public void setReferredby(String referredby) {
        this.referredby = referredby;
    }
    
    @Column(name="serialno")
    public Long getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Long serialno) {
        this.serialno = serialno;
    }
    
    @Column(name="lipid")
    public String getLipid() {
        return this.lipid;
    }
    
    public void setLipid(String lipid) {
        this.lipid = lipid;
    }
    
    @Column(name="lipid1")
    public String getLipid1() {
        return this.lipid1;
    }
    
    public void setLipid1(String lipid1) {
        this.lipid1 = lipid1;
    }
    
    @Column(name="lipid2")
    public String getLipid2() {
        return this.lipid2;
    }
    
    public void setLipid2(String lipid2) {
        this.lipid2 = lipid2;
    }
    
    @Column(name="lipid3")
    public String getLipid3() {
        return this.lipid3;
    }
    
    public void setLipid3(String lipid3) {
        this.lipid3 = lipid3;
    }
    
    @Column(name="lipid4")
    public String getLipid4() {
        return this.lipid4;
    }
    
    public void setLipid4(String lipid4) {
        this.lipid4 = lipid4;
    }
    
    @Column(name="remarks")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
    @Column(name="labtech", length=150)
    public String getLabtech() {
        return this.labtech;
    }
    
    public void setLabtech(String labtech) {
        this.labtech = labtech;
    }
    
    @Column(name="ddate")
    public String getDdate() {
        return this.ddate;
    }
    
    public void setDdate(String ddate) {
        this.ddate = ddate;
    }




}


