package com.model.dispensedmedicinebill.dto;
// Generated Aug 14, 2012 12:27:55 PM by Hibernate Tools 3.2.1.GA

import com.model.dispense.dto.Dispense;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dispensedmedicinebill generated by hbm2java
 */
@Entity
@Table(name = "dispensedmedicinebill", schema = "public")
@SequenceGenerator(name = "dispensedmedicinebill_seq", sequenceName = "dispensedmedicinebill_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Dispensedmedicinebill implements java.io.Serializable {

    private long id;
    private Dispense dispense;
    private Date publisheddate;
    private BigDecimal amount;
    private BigDecimal consultationamount;
    private BigDecimal miscellanousamount;
    private BigDecimal medicineamount;
    private BigDecimal billvaluebeforediscount;
    private Long discountparcentage;
    private BigDecimal discountedvalue;
    private String doctordepartment;
    private String doctorname;

    private BigDecimal cgst;
     private BigDecimal sgst;
     private BigDecimal igst;
     private long gst;
     private BigDecimal totaltaxvalue;

    /**
     *
     */
    public Dispensedmedicinebill() {
    }

    public Dispensedmedicinebill(long id,  Date publisheddate, BigDecimal amount, BigDecimal consultationamount, BigDecimal miscellanousamount, BigDecimal medicineamount, BigDecimal billvaluebeforediscount, Long discountparcentage, BigDecimal discountedvalue, String doctordepartment, String doctorname, BigDecimal cgst, BigDecimal sgst, BigDecimal igst,long gst, BigDecimal totaltaxvalue) {
       this.id = id;
       
       this.publisheddate = publisheddate;
       this.amount = amount;
       this.consultationamount = consultationamount;
       this.miscellanousamount = miscellanousamount;
       this.medicineamount = medicineamount;
       this.billvaluebeforediscount = billvaluebeforediscount;
       this.discountparcentage = discountparcentage;
       this.discountedvalue = discountedvalue;
       this.doctordepartment = doctordepartment;
       this.doctorname = doctorname;
       this.cgst = cgst;
       this.sgst = sgst;
       this.igst = igst;
       this.gst = gst;
       this.totaltaxvalue = totaltaxvalue;
    }

    /**
     *
     * @return
     */
    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(generator = "dispensedmedicinebill_seq")
    public long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "dispenseid", nullable = false)
    public Dispense getDispense() {
        return this.dispense;
    }

    /**
     *
     * @param dispense
     */
    public void setDispense(Dispense dispense) {
        this.dispense = dispense;
    }

    /**
     *
     * @return
     */
    @Temporal(TemporalType.TIME)
    @Column(name = "publisheddate", nullable = false, length = 15)
    public Date getPublisheddate() {
        return this.publisheddate;
    }

    /**
     *
     * @param publisheddate
     */
    public void setPublisheddate(Date publisheddate) {
        this.publisheddate = publisheddate;
    }

    /**
     *
     * @return
     */
    @Column(name = "amount", precision = 20)
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     *
     * @param amount
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     *
     * @return
     */
    @Column(name = "consultationamount", precision = 20)
    public BigDecimal getConsultationamount() {
        return consultationamount;
    }

    /**
     *
     * @param consultationamount
     */
    public void setConsultationamount(BigDecimal consultationamount) {
        this.consultationamount = consultationamount;
    }

    /**
     *
     * @return
     */
    @Column(name = "miscellanousamount", precision = 20)
    public BigDecimal getMiscellanousamount() {
        return miscellanousamount;
    }

    /**
     *
     * @param miscellanousamount
     */
    public void setMiscellanousamount(BigDecimal miscellanousamount) {
        this.miscellanousamount = miscellanousamount;
    }

    /**
     *
     * @return
     */
    @Column(name="medicineamount", precision=20)
    public BigDecimal getMedicineamount() {
        return medicineamount;
    }

    /**
     *
     * @param medicineamount
     */
    public void setMedicineamount(BigDecimal medicineamount) {
        this.medicineamount = medicineamount;
    }

    @Column(name="billvaluebeforediscount", precision=20)
    public BigDecimal getBillvaluebeforediscount() {
        return this.billvaluebeforediscount;
    }

    public void setBillvaluebeforediscount(BigDecimal
billvaluebeforediscount) {
        this.billvaluebeforediscount = billvaluebeforediscount;
    }

    @Column(name="discountparcentage")
    public Long getDiscountparcentage() {
        return this.discountparcentage;
    }

    public void setDiscountparcentage(Long discountparcentage) {
        this.discountparcentage = discountparcentage;
    }

    @Column(name="discountedvalue", precision=20)
    public BigDecimal getDiscountedvalue() {
        return this.discountedvalue;
    }

    public void setDiscountedvalue(BigDecimal discountedvalue) {
        this.discountedvalue = discountedvalue;
    }
    @Column(name="doctordepartment", length=300)
    public String getDoctordepartment() {
        return this.doctordepartment;
    }

    public void setDoctordepartment(String doctordepartment) {
        this.doctordepartment = doctordepartment;
    }

    @Column(name="doctorname", length=300)
    public String getDoctorname() {
        return this.doctorname;
    }

    public void setDoctorname(String doctorname) {
        this.doctorname = doctorname;
    }

    @Column(name="cgst", precision=20)
    public BigDecimal getCgst() {
        return this.cgst;
    }

    public void setCgst(BigDecimal cgst) {
        this.cgst = cgst;
    }

    @Column(name="sgst", precision=20)
    public BigDecimal getSgst() {
        return this.sgst;
    }

    public void setSgst(BigDecimal sgst) {
        this.sgst = sgst;
    }

    @Column(name="igst", precision=20)
    public BigDecimal getIgst() {
        return this.igst;
    }

    public void setIgst(BigDecimal igst) {
        this.igst = igst;
    }

    @Column(name="totaltaxvalue", precision=20)
    public BigDecimal getTotaltaxvalue() {
        return this.totaltaxvalue;
    }

    public void setTotaltaxvalue(BigDecimal totaltaxvalue) {
        this.totaltaxvalue = totaltaxvalue;
    }

    @Column(name="gst")
    public long getGst() {
        return this.gst;
    }

    public void setGst(long gst) {
        this.gst = gst;
    }
}

