package com.model.redispensedmedicinebill.dto;
// Generated 22 Aug, 2017 12:52:15 PM by Hibernate Tools 3.2.1.GA


import com.model.redispense.dto.Redispense;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Redispensedmedicinebill generated by hbm2java
 */
@Entity
@Table(name="redispensedmedicinebill"
    ,schema="public"
)
@SequenceGenerator(name = "redispensedmedicinebill_seq", sequenceName = "redispensedmedicinebill_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Redispensedmedicinebill  implements java.io.Serializable {


     private long id;
     private Redispense redispense;
     private Date publisheddate;
     private BigDecimal amount;
     private BigDecimal medicineamount;
     private BigDecimal billvaluebeforediscount;
     private Long discountparcentage;
     private BigDecimal discountedvalue;
     private String doctordepartment;
     private String doctorname;
     private BigDecimal cgst;
     private BigDecimal sgst;
     private BigDecimal igst;
     private BigDecimal totaltaxvalue;
     private long gst;

    public Redispensedmedicinebill() {
    }

	
    public Redispensedmedicinebill(long id, Redispense redispense, Date publisheddate) {
        this.id = id;
        this.redispense = redispense;
        this.publisheddate = publisheddate;
    }
    public Redispensedmedicinebill(long id, Redispense redispense, Date publisheddate, BigDecimal amount, BigDecimal medicineamount, BigDecimal billvaluebeforediscount, Long discountparcentage, BigDecimal discountedvalue, String doctordepartment, String doctorname, BigDecimal cgst, BigDecimal sgst, BigDecimal igst, BigDecimal totaltaxvalue, long gst) {
       this.id = id;
       this.redispense = redispense;
       this.publisheddate = publisheddate;
       this.amount = amount;
       this.medicineamount = medicineamount;
       this.billvaluebeforediscount = billvaluebeforediscount;
       this.discountparcentage = discountparcentage;
       this.discountedvalue = discountedvalue;
       this.doctordepartment = doctordepartment;
       this.doctorname = doctorname;
       this.cgst = cgst;
       this.sgst = sgst;
       this.igst = igst;
       this.totaltaxvalue = totaltaxvalue;
       this.gst = gst;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
     @GeneratedValue(generator = "redispensedmedicinebill_seq")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="redispenseid", nullable=false)
    public Redispense getRedispense() {
        return this.redispense;
    }
    
    public void setRedispense(Redispense redispense) {
        this.redispense = redispense;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="publisheddate", nullable=false, length=15)
    public Date getPublisheddate() {
        return this.publisheddate;
    }
    
    public void setPublisheddate(Date publisheddate) {
        this.publisheddate = publisheddate;
    }
    
    @Column(name="amount", precision=20)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    
    @Column(name="medicineamount", precision=20)
    public BigDecimal getMedicineamount() {
        return this.medicineamount;
    }
    
    public void setMedicineamount(BigDecimal medicineamount) {
        this.medicineamount = medicineamount;
    }
    
    @Column(name="billvaluebeforediscount", precision=20)
    public BigDecimal getBillvaluebeforediscount() {
        return this.billvaluebeforediscount;
    }
    
    public void setBillvaluebeforediscount(BigDecimal billvaluebeforediscount) {
        this.billvaluebeforediscount = billvaluebeforediscount;
    }
    
    @Column(name="discountparcentage")
    public Long getDiscountparcentage() {
        return this.discountparcentage;
    }
    
    public void setDiscountparcentage(Long discountparcentage) {
        this.discountparcentage = discountparcentage;
    }
    
    @Column(name="discountedvalue", precision=20)
    public BigDecimal getDiscountedvalue() {
        return this.discountedvalue;
    }
    
    public void setDiscountedvalue(BigDecimal discountedvalue) {
        this.discountedvalue = discountedvalue;
    }
    
    @Column(name="doctordepartment", length=300)
    public String getDoctordepartment() {
        return this.doctordepartment;
    }
    
    public void setDoctordepartment(String doctordepartment) {
        this.doctordepartment = doctordepartment;
    }
    
    @Column(name="doctorname", length=300)
    public String getDoctorname() {
        return this.doctorname;
    }
    
    public void setDoctorname(String doctorname) {
        this.doctorname = doctorname;
    }
    
    @Column(name="cgst", precision=20)
    public BigDecimal getCgst() {
        return this.cgst;
    }
    
    public void setCgst(BigDecimal cgst) {
        this.cgst = cgst;
    }
    
    @Column(name="sgst", precision=20)
    public BigDecimal getSgst() {
        return this.sgst;
    }
    
    public void setSgst(BigDecimal sgst) {
        this.sgst = sgst;
    }
    
    @Column(name="igst", precision=20)
    public BigDecimal getIgst() {
        return this.igst;
    }
    
    public void setIgst(BigDecimal igst) {
        this.igst = igst;
    }
    
    @Column(name="totaltaxvalue", precision=20)
    public BigDecimal getTotaltaxvalue() {
        return this.totaltaxvalue;
    }
    
    public void setTotaltaxvalue(BigDecimal totaltaxvalue) {
        this.totaltaxvalue = totaltaxvalue;
    }
    
    @Column(name="gst")
    public long getGst() {
        return this.gst;
    }
    
    public void setGst(long gst) {
        this.gst = gst;
    }




}


