package com.model.lab.dto;
// Generated Jul 17, 2017 1:13:36 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;
import javax.persistence.GeneratedValue;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lab generated by hbm2java
 */
@Entity
@Table(name = "LAB", schema = "public")
@SequenceGenerator(name = "lab_seq", sequenceName = "lab_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Lab implements java.io.Serializable {

    private long id;
    private String name;
    private Short age;
    private String sex;
    private Long cardno;
    private String referredby;
    private Long serialno;
    private Date ddate;
    private String result1;
    private String result2;
    private String result3;
    private String result4;
    private String result5;
    private String result6;
    private String result7;
    private String result8;
    private String result9;
    private String result10;
    private String result11;
    private String result12;
    private String result13;
    private String result14;
    private String result15;
    private String result16;
    private String result17;
    private String result18;
    private String result19;
    private String result20;
    private String result21;
    private String result22;
    private String result23;
    private String result24;
    private String result25;
    private String result26;
    private String result27;
    private String result28;
    private String result29;
    private String result30;
    private String result31;
    private String result32;
    private String result33;
    private String result34;
    private String result35;
    private String result36;
    private String result37;
    private String result38;
    private String result39;
    private String result40;
    private String result41;
    private String result42;
    private String result43;
    private String result44;
    private String result45;
    private String result46;
    private String result47;
    private String result50;

    @Column(name = "result50")
    public String getResult50() {
        return result50;
    }

    public void setResult50(String result50) {
        this.result50 = result50;
    }

    @Column(name = "result48")
    public String getResult48() {
        return result48;
    }

    public void setResult48(String result48) {
        this.result48 = result48;
    }

    @Column(name = "result49")
    public String getResult49() {
        return result49;
    }

    public void setResult49(String result49) {
        this.result49 = result49;
    }
    private String result48;
    private String result49;

    @Column(name = "result31")
    public String getResult31() {
        return result31;
    }

    public void setResult31(String result31) {
        this.result31 = result31;
    }

    @Column(name = "result32")
    public String getResult32() {
        return result32;
    }

    public void setResult32(String result32) {
        this.result32 = result32;
    }

    @Column(name = "result33")
    public String getResult33() {
        return result33;
    }

    public void setResult33(String result33) {
        this.result33 = result33;
    }

    @Column(name = "result34")
    public String getResult34() {
        return result34;
    }

    public void setResult34(String result34) {
        this.result34 = result34;
    }

    @Column(name = "result35")
    public String getResult35() {
        return result35;
    }

    public void setResult35(String result35) {
        this.result35 = result35;
    }

    @Column(name = "result36")
    public String getResult36() {
        return result36;
    }

    public void setResult36(String result36) {
        this.result36 = result36;
    }

    @Column(name = "result37")
    public String getResult37() {
        return result37;
    }

    public void setResult37(String result37) {
        this.result37 = result37;
    }

    @Column(name = "result38")
    public String getResult38() {
        return result38;
    }

    public void setResult38(String result38) {
        this.result38 = result38;
    }

    @Column(name = "result39")
    public String getResult39() {
        return result39;
    }

    public void setResult39(String result39) {
        this.result39 = result39;
    }

    @Column(name = "result40")
    public String getResult40() {
        return result40;
    }

    public void setResult40(String result40) {
        this.result40 = result40;
    }

    @Column(name = "result41")
    public String getResult41() {
        return result41;
    }

    public void setResult41(String result41) {
        this.result41 = result41;
    }

    @Column(name = "result42")
    public String getResult42() {
        return result42;
    }

    public void setResult42(String result42) {
        this.result42 = result42;
    }

    @Column(name = "result43")
    public String getResult43() {
        return result43;
    }

    public void setResult43(String result43) {
        this.result43 = result43;
    }

    @Column(name = "result44")
    public String getResult44() {
        return result44;
    }

    public void setResult44(String result44) {
        this.result44 = result44;
    }

    @Column(name = "result45")
    public String getResult45() {
        return result45;
    }

    public void setResult45(String result45) {
        this.result45 = result45;
    }

    @Column(name = "result46")
    public String getResult46() {
        return result46;
    }

    public void setResult46(String result46) {
        this.result46 = result46;
    }

    @Column(name = "result47")
    public String getResult47() {
        return result47;
    }

    public void setResult47(String result47) {
        this.result47 = result47;
    }

    public Lab() {
    }

    public Lab(long id) {
        this.id = id;
    }

    public Lab(long id, String name, Short age, String sex, Long cardno, String referredby, Long serialno, String result1, String result2, String result3, String result4, String result5, String result6, String result7, String result8, String result9, String result10, String result11, String result12, String result13, String result14, String result15, String result16, String result17, String result18, String result19, String result20, String result21, String result22, String result23, String result24, String result25, String result26, String result27, String result28, String result29, String result30, String result31, String result32, String result33, String result34, String result35, String result36, String result37, String result38, String result39, String result40, String result41, String result42, String result43, String result44, String result45, String result46, String result47, String result48, String result49, String result50, Date ddate) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.cardno = cardno;
        this.referredby = referredby;
        this.serialno = serialno;

        this.result1 = result1;
        this.result2 = result2;
        this.result3 = result3;
        this.result4 = result4;
        this.result5 = result5;
        this.result6 = result6;
        this.result7 = result7;
        this.result8 = result8;
        this.result9 = result9;
        this.result10 = result10;
        this.result11 = result11;
        this.result12 = result12;
        this.result13 = result13;
        this.result14 = result14;
        this.result15 = result15;
        this.result16 = result16;
        this.result17 = result17;
        this.result18 = result18;
        this.result19 = result19;
        this.result20 = result20;
        this.result21 = result21;
        this.result22 = result22;
        this.result23 = result23;
        this.result24 = result24;
        this.result25 = result25;
        this.result26 = result26;
        this.result27 = result27;
        this.result28 = result28;
        this.result29 = result29;
        this.result30 = result30;
        this.result31 = result31;
        this.result32 = result32;
        this.result33 = result33;
        this.result34 = result34;
        this.result35 = result35;
        this.result36 = result36;
        this.result37 = result37;
        this.result38 = result38;
        this.result39 = result39;
        this.result40 = result40;
        this.result41 = result41;
        this.result42 = result42;
        this.result43 = result43;
        this.result44 = result44;
        this.result45 = result45;
        this.result46 = result46;
        this.result47 = result47;
        this.result48 = result48;
        this.result49 = result49;
        this.result50 = result50;

    }

    @Column(name = "result11")
    public String getResult11() {
        return result11;
    }

    public void setResult11(String result11) {
        this.result11 = result11;
    }

    @Column(name = "result12")
    public String getResult12() {
        return result12;
    }

    public void setResult12(String result12) {
        this.result12 = result12;
    }

    @Column(name = "result13")
    public String getResult13() {
        return result13;
    }

    public void setResult13(String result13) {
        this.result13 = result13;
    }

    @Column(name = "result14")
    public String getResult14() {
        return result14;
    }

    public void setResult14(String result14) {
        this.result14 = result14;
    }

    @Column(name = "result15")
    public String getResult15() {
        return result15;
    }

    public void setResult15(String result15) {
        this.result15 = result15;
    }

    @Column(name = "result16")
    public String getResult16() {
        return result16;
    }

    public void setResult16(String result16) {
        this.result16 = result16;
    }

    @Column(name = "result17")
    public String getResult17() {
        return result17;
    }

    public void setResult17(String result17) {
        this.result17 = result17;
    }

    @Column(name = "result18")
    public String getResult18() {
        return result18;
    }

    public void setResult18(String result18) {
        this.result18 = result18;
    }

    @Column(name = "result19")
    public String getResult19() {
        return result19;
    }

    public void setResult19(String result19) {
        this.result19 = result19;
    }

    @Column(name = "result20")
    public String getResult20() {
        return result20;
    }

    public void setResult20(String result20) {
        this.result20 = result20;
    }

    @Column(name = "result21")
    public String getResult21() {
        return result21;
    }

    public void setResult21(String result21) {
        this.result21 = result21;
    }

    @Column(name = "result22")
    public String getResult22() {
        return result22;
    }

    public void setResult22(String result22) {
        this.result22 = result22;
    }

    @Column(name = "result23")
    public String getResult23() {
        return result23;
    }

    public void setResult23(String result23) {
        this.result23 = result23;
    }

    @Column(name = "result24")
    public String getResult24() {
        return result24;
    }

    public void setResult24(String result24) {
        this.result24 = result24;
    }

    @Column(name = "result25")
    public String getResult25() {
        return result25;
    }

    public void setResult25(String result25) {
        this.result25 = result25;
    }

    @Column(name = "result26")
    public String getResult26() {
        return result26;
    }

    public void setResult26(String result26) {
        this.result26 = result26;
    }

    @Column(name = "result27")
    public String getResult27() {
        return result27;
    }

    public void setResult27(String result27) {
        this.result27 = result27;
    }

    @Column(name = "result28")
    public String getResult28() {
        return result28;
    }

    public void setResult28(String result28) {
        this.result28 = result28;
    }

    @Column(name = "result29")
    public String getResult29() {
        return result29;
    }

    public void setResult29(String result29) {
        this.result29 = result29;
    }

    @Column(name = "result30")
    public String getResult30() {
        return result30;
    }

    public void setResult30(String result30) {
        this.result30 = result30;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(generator = "lab_seq")
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "name", length = 150)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "age")
    public Short getAge() {
        return this.age;
    }

    public void setAge(Short age) {
        this.age = age;
    }

    @Column(name = "sex", length = 50)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name = "cardno")
    public Long getCardno() {
        return cardno;
    }

    /**
     * @param cardno the cardno to set
     */
    public void setCardno(Long cardno) {
        this.cardno = cardno;
    }

    @Column(name = "referredby", length = 150)
    public String getReferredby() {
        return this.referredby;
    }

    public void setReferredby(String referredby) {
        this.referredby = referredby;
    }

    @Column(name = "serialno")
    public Long getSerialno() {
        return this.serialno;
    }

    public void setSerialno(Long serialno) {
        this.serialno = serialno;
    }

    @Column(name = "result1")
    public String getResult1() {
        return this.result1;
    }

    public void setResult1(String result1) {
        this.result1 = result1;
    }

    @Column(name = "result2")
    public String getResult2() {
        return this.result2;
    }

    public void setResult2(String result2) {
        this.result2 = result2;
    }

    @Column(name = "result3")
    public String getResult3() {
        return this.result3;
    }

    public void setResult3(String result3) {
        this.result3 = result3;
    }

    @Column(name = "result4")
    public String getResult4() {
        return this.result4;
    }

    public void setResult4(String result4) {
        this.result4 = result4;
    }

    @Column(name = "result5")
    public String getResult5() {
        return this.result5;
    }

    public void setResult5(String result5) {
        this.result5 = result5;
    }

    @Column(name = "result6")
    public String getResult6() {
        return this.result6;
    }

    public void setResult6(String result6) {
        this.result6 = result6;
    }

    @Column(name = "result7")
    public String getResult7() {
        return this.result7;
    }

    public void setResult7(String result7) {
        this.result7 = result7;
    }

    @Column(name = "result8")
    public String getResult8() {
        return this.result8;
    }

    public void setResult8(String result8) {
        this.result8 = result8;
    }

    @Column(name = "result9")
    public String getResult9() {
        return this.result9;
    }

    public void setResult9(String result9) {
        this.result9 = result9;
    }

    @Column(name = "result10")
    public String getResult10() {
        return this.result10;
    }

    public void setResult10(String result10) {
        this.result9 = result10;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ddate", length = 13)
    public Date getDdate() {
        return this.ddate;
    }

    public void setDdate(Date ddate) {
        this.ddate = ddate;
    }
}


