package com.model.roomsetup.dto;
// Generated Jul 11, 2016 5:39:12 PM by Hibernate Tools 3.2.1.GA


import com.model.BuildingType.dto.Buildingtypesetup;
import com.model.roomndbedssetup.dto.Roomndbedsetup;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Roomsetup generated by hbm2java
 */
@Entity
@Table(name="roomsetup"
    ,schema="public"
)
        @SequenceGenerator(name = "roomsetup_seq", sequenceName = "roomsetup_seq")
         @org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Roomsetup  implements java.io.Serializable {


     private long roomsetupid;
     private Buildingtypesetup buildingtypesetup;
     private long floorno;
     private long noofrooms;
     private Set<Roomndbedsetup> roomndbedsetups = new HashSet<Roomndbedsetup>(0);

    public Roomsetup() {
    }


    public Roomsetup(long roomsetupid, Buildingtypesetup buildingtypesetup, long floorno, long noofrooms) {
        this.roomsetupid = roomsetupid;
        this.buildingtypesetup = buildingtypesetup;
        this.floorno = floorno;
        this.noofrooms = noofrooms;
    }
    public Roomsetup(long roomsetupid, Buildingtypesetup buildingtypesetup, long floorno, long noofrooms, Set<Roomndbedsetup> roomndbedsetups) {
       this.roomsetupid = roomsetupid;
       this.buildingtypesetup = buildingtypesetup;
       this.floorno = floorno;
       this.noofrooms = noofrooms;
       this.roomndbedsetups = roomndbedsetups;
    }

     @Id

    @Column(name="roomsetupid", unique=true, nullable=false)
     @GeneratedValue(generator = "roomsetup_seq")
    public long getRoomsetupid() {
        return this.roomsetupid;
    }

    public void setRoomsetupid(long roomsetupid) {
        this.roomsetupid = roomsetupid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="buildingid", nullable=false)
    public Buildingtypesetup getBuildingtypesetup() {
        return this.buildingtypesetup;
    }

    public void setBuildingtypesetup(Buildingtypesetup buildingtypesetup) {
        this.buildingtypesetup = buildingtypesetup;
    }

    @Column(name="floorno", nullable=false)
    public long getFloorno() {
        return this.floorno;
    }

    public void setFloorno(long floorno) {
        this.floorno = floorno;
    }

    @Column(name="noofrooms", nullable=false)
    public long getNoofrooms() {
        return this.noofrooms;
    }

    public void setNoofrooms(long noofrooms) {
        this.noofrooms = noofrooms;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="roomsetup")
    public Set<Roomndbedsetup> getRoomndbedsetups() {
        return this.roomndbedsetups;
    }

    public void setRoomndbedsetups(Set<Roomndbedsetup> roomndbedsetups) {
        this.roomndbedsetups = roomndbedsetups;
    }




}
