package com.model.token.dto;
// Generated Jun 20, 2016 1:44:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tokenlist generated by hbm2java
 */
@Entity
@Table(name="tokenlist"
    ,schema="public"
)

        @SequenceGenerator(name = "tokenlist_seq", sequenceName = "tokenlist_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Tokenlist  implements java.io.Serializable {


     private long tokenid;
     private long tokenno;
     private Date tdate;

    public Tokenlist() {
    }

    public Tokenlist(long tokenid, long tokenno, Date tdate) {
       this.tokenid = tokenid;
       this.tokenno = tokenno;
       this.tdate = tdate;
    }
   
     @Id 
    
    @Column(name="tokenid", unique=true, nullable=false)
      @GeneratedValue(generator = "tokenlist_seq")
    public long getTokenid() {
        return this.tokenid;
    }
    
    public void setTokenid(long tokenid) {
        this.tokenid = tokenid;
    }
    
    @Column(name="tokenno", nullable=false)
    public long getTokenno() {
        return this.tokenno;
    }
    
    public void setTokenno(long tokenno) {
        this.tokenno = tokenno;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="tdate", nullable=false, length=13)
    public Date getTdate() {
        return this.tdate;
    }
    
    public void setTdate(Date tdate) {
        this.tdate = tdate;
    }




}


