package com.model.detailInvestigationBill.dto;
// Generated Sep 1, 2014 3:04:02 PM by Hibernate Tools 3.2.1.GA


import com.model.investigation.dto.Investigation;
import com.model.investigationbill.dto.Investigationbill;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detailsinvestigationbill generated by hbm2java
 */
@Entity
@Table(name="detailsinvestigationbill"
    ,schema="public"
)
         @SequenceGenerator(name = "detailsinvestigationbill_seq", sequenceName = "detailsinvestigationbill_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Detailsinvestigationbill  implements java.io.Serializable {


     private long detailsinvestigationbillid;
     private Investigationbill investigationbill;
     private Investigation investigation;
     private Date detailsinvestigationbilldate;
     private BigDecimal detailsinvestigationbillcharge;
      private BigDecimal advancedtakenchild;
     private Long dueamount;

    public Detailsinvestigationbill() {
    }

	
    public Detailsinvestigationbill(long detailsinvestigationbillid, Investigationbill investigationbill, Investigation investigation) {
        this.detailsinvestigationbillid = detailsinvestigationbillid;
        this.investigationbill = investigationbill;
        this.investigation = investigation;
    }
    public Detailsinvestigationbill(long detailsinvestigationbillid, Investigationbill investigationbill, Investigation investigation, Date detailsinvestigationbilldate, BigDecimal detailsinvestigationbillcharge) {
       this.detailsinvestigationbillid = detailsinvestigationbillid;
       this.investigationbill = investigationbill;
       this.investigation = investigation;
       this.detailsinvestigationbilldate = detailsinvestigationbilldate;
       this.detailsinvestigationbillcharge = detailsinvestigationbillcharge;
    }

    public Detailsinvestigationbill(long detailsinvestigationbillid, Investigationbill investigationbill, Investigation investigation, Date detailsinvestigationbilldate, BigDecimal detailsinvestigationbillcharge, BigDecimal advancedtakenchild, Long dueamount) {
       this.detailsinvestigationbillid = detailsinvestigationbillid;
       this.investigationbill = investigationbill;
       this.investigation = investigation;
       this.detailsinvestigationbilldate = detailsinvestigationbilldate;
       this.detailsinvestigationbillcharge = detailsinvestigationbillcharge;
       this.advancedtakenchild = advancedtakenchild;
       this.dueamount = dueamount;
    }
   
     @Id 
    
    @Column(name="detailsinvestigationbillid", unique=true, nullable=false)
     @GeneratedValue(generator = "detailsinvestigationbill_seq")
    public long getDetailsinvestigationbillid() {
        return this.detailsinvestigationbillid;
    }
    
    public void setDetailsinvestigationbillid(long detailsinvestigationbillid) {
        this.detailsinvestigationbillid = detailsinvestigationbillid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="investigationbillid", nullable=false)
    public Investigationbill getInvestigationbill() {
        return this.investigationbill;
    }
    
    public void setInvestigationbill(Investigationbill investigationbill) {
        this.investigationbill = investigationbill;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="investigationid", nullable=false)
    public Investigation getInvestigation() {
        return this.investigation;
    }
    
    public void setInvestigation(Investigation investigation) {
        this.investigation = investigation;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="detailsinvestigationbilldate", length=13)
    public Date getDetailsinvestigationbilldate() {
        return this.detailsinvestigationbilldate;
    }
    
    public void setDetailsinvestigationbilldate(Date detailsinvestigationbilldate) {
        this.detailsinvestigationbilldate = detailsinvestigationbilldate;
    }
    
    @Column(name="detailsinvestigationbillcharge", precision=20)
    public BigDecimal getDetailsinvestigationbillcharge() {
        return this.detailsinvestigationbillcharge;
    }
    
    public void setDetailsinvestigationbillcharge(BigDecimal detailsinvestigationbillcharge) {
        this.detailsinvestigationbillcharge = detailsinvestigationbillcharge;
    }

    @Column(name="advancedtakenchild", precision=20)
    public BigDecimal getAdvancedtakenchild() {
        return this.advancedtakenchild;
    }

    public void setAdvancedtakenchild(BigDecimal advancedtakenchild) {
        this.advancedtakenchild = advancedtakenchild;
    }

    @Column(name="dueamount")
    public Long getDueamount() {
        return this.dueamount;
    }

    public void setDueamount(Long dueamount) {
        this.dueamount = dueamount;
    }




}


