package com.model.bloodtransfucion.dto;
// Generated 3 Jul, 2017 4:59:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bloodtransfucion generated by hbm2java
 */
@Entity
@Table(name="bloodtransfucion"
    ,schema="public"
)
@SequenceGenerator(name = "bloodtransfucion_seq", sequenceName = "bloodtransfucion_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Bloodtransfucion  implements java.io.Serializable {


     private long id;
     private String pateintname;
     private String warddept;
     private String warddep;
     private Long bedno;
     private Short age;
     private String sex;
     private String ptsdoctor;
     private String bloodgroup;
     private String ddate;
     private String donors;
     private Long bottleno;
     private String bgroup;
     private String hiv;
     private String hcv;
     private String hbsag;
     private String vdrl;
     private String mp;

     private String donors1;
     private Long bottleno1;
     private String bgroup1;
     private String hiv1;
     private String hcv1;
     private String hbsag1;
     private String vdrl1;
     private String mp1;
     private String donors2;
     private Long bottleno2;
     private String bgroup2;
     private String hiv2;
     private String hcv2;
     private String hbsag2;
     private String vdrl2;
     private String mp2;
     private Long qualityofblood;
     private String sd;
    private String rh;
     private String ml;
     private String ml1;
     private String ml2;
     private String ml3;
    private  String ddate1;
    private String ddate2;
    


    public Bloodtransfucion() {
    }

	
    public Bloodtransfucion(long id) {
        this.id = id;
    }
    public Bloodtransfucion(long id, String ddate2, String pateintname, String warddept, String warddep, Long bedno, Short age, String sex, String ptsdoctor, String bloodgroup, String rh, String ddate, String ddate1, String donors, Long bottleno, String bgroup, String hiv, String hcv, String hbsag, String vdrl, String mp, String donors1, Long bottleno1, String bgroup1, String hiv1, String hcv1, String hbsag1, String vdrl1, String mp1, String donors2, Long bottleno2, String bgroup2, String hiv2, String hcv2, String hbsag2, String vdrl2, String mp2, Long qualityofblood, String ml, String ml1, String ml2, String ml3, String sd) {
       this.id = id;
       this.pateintname = pateintname;
       this.warddept = warddept;
       this.warddep = warddep;
       this.bedno = bedno;
       this.age = age;
       this.sex = sex;
       this.ptsdoctor = ptsdoctor;
       this.bloodgroup = bloodgroup;
       this.rh = rh;
       this.ddate = ddate;
       this.ddate = ddate1;
       this.ddate = ddate2;
       this.donors = donors;
       this.bottleno = bottleno;
       this.bgroup = bgroup;
       this.hiv = hiv;
       this.hcv = hcv;
       this.hbsag = hbsag;
       this.vdrl = vdrl;
       this.mp = mp;
       this.donors1 = donors1;
       this.bottleno1 = bottleno1;
       this.bgroup1 = bgroup1;
       this.hiv1 = hiv1;
       this.hcv1 = hcv1;
       this.hbsag1 = hbsag1;
       this.vdrl1 = vdrl1;
       this.mp1 = mp1;

       this.donors2 = donors2;
       this.bottleno2 = bottleno2;
       this.bgroup2 = bgroup2;
       this.hiv2 = hiv2;
       this.hcv2 = hcv2;
       this.hbsag2 = hbsag2;
       this.vdrl2 = vdrl2;
       this.mp2 = mp2;
       this.qualityofblood = qualityofblood;
       this.sd = sd;
       this.ml = ml;
       this.ml1 = ml1;
       this.ml2 = ml2;
       this.ml3 = ml3;

    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(generator = "bloodtransfucion_seq")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="pateintname", length=150)
    public String getPateintname() {
        return this.pateintname;
    }
    
    public void setPateintname(String pateintname) {
        this.pateintname = pateintname;
    }
    
    @Column(name="warddept")
    public String getWarddept() {
        return this.warddept;
    }
    
    public void setWarddept(String warddept) {
        this.warddept = warddept;
    }
    
    @Column(name="warddep")
    public String getWarddep() {
        return this.warddep;
    }
    
    public void setWarddep(String warddep) {
        this.warddep = warddep;
    }
    
    @Column(name="bedno")
    public Long getBedno() {
        return this.bedno;
    }
    
    public void setBedno(Long bedno) {
        this.bedno = bedno;
    }
    
    @Column(name="age")
    public Short getAge() {
        return this.age;
    }
    
    public void setAge(Short age) {
        this.age = age;
    }
    
    @Column(name="sex", length=10)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    
    @Column(name="ptsdoctor", length=150)
    public String getPtsdoctor() {
        return this.ptsdoctor;
    }
    
    public void setPtsdoctor(String ptsdoctor) {
        this.ptsdoctor = ptsdoctor;
    }
    
    @Column(name="bloodgroup", length=30)
    public String getBloodgroup() {
        return this.bloodgroup;
    }
    
    public void setBloodgroup(String bloodgroup) {
        this.bloodgroup = bloodgroup;
    }
    @Column(name="rh")
    public String getRh() {
        return this.rh;
    }
    
    public void setRh(String rh) {
        this.rh = rh;
    }

    @Column(name="ddate")
    public String getDdate() {
        return this.ddate;
    }

    public void setDdate(String ddate) {
        this.ddate = ddate;
    }

    @Column(name="ddate1")
    public String getDdate1() {
        return this.ddate1;
    }

    public void setDdate1(String ddate1) {
        this.ddate1 = ddate1;
    }
    @Column(name="ddate2")
    public String getDdate2() {
        return this.ddate2;
    }

    public void setDdate2(String ddate2) {
        this.ddate2 = ddate2;
    }

    @Column(name="donors")
    public String getDonors() {
        return this.donors;
    }
    
    public void setDonors(String donors) {
        this.donors = donors;
    }
    
    @Column(name="bottleno")
    public Long getBottleno() {
        return this.bottleno;
    }
    
    public void setBottleno(Long bottleno) {
        this.bottleno = bottleno;
    }
    
    @Column(name="bgroup", length=30)
    public String getBgroup() {
        return this.bgroup;
    }
    
    public void setBgroup(String bgroup) {
        this.bgroup = bgroup;
    }
    
    @Column(name="hiv")
    public String getHiv() {
        return this.hiv;
    }
    
    public void setHiv(String hiv) {
        this.hiv = hiv;
    }
    
    @Column(name="hcv")
    public String getHcv() {
        return this.hcv;
    }
    
    public void setHcv(String hcv) {
        this.hcv = hcv;
    }
    
    @Column(name="hbsag")
    public String getHbsag() {
        return this.hbsag;
    }
    
    public void setHbsag(String hbsag) {
        this.hbsag = hbsag;
    }
    
    @Column(name="vdrl")
    public String getVdrl() {
        return this.vdrl;
    }
    
    public void setVdrl(String vdrl) {
        this.vdrl = vdrl;
    }
    
    @Column(name="mp")
    public String getMp() {
        return this.mp;
    }
    
    public void setMp(String mp) {
        this.mp = mp;
    }


    @Column(name="donors1")
    public String getDonors1() {
        return this.donors1;
    }

     public void setDonors1(String donors1) {
        this.donors1 = donors1;
    }

    @Column(name="bottleno1")
    public Long getBottleno1() {
        return this.bottleno1;
    }

    public void setBottleno1(Long bottleno1) {
        this.bottleno1 = bottleno1;
    }

    @Column(name="bgroup1", length=30)
    public String getBgroup1() {
        return this.bgroup1;
    }

    public void setBgroup1(String bgroup1) {
        this.bgroup1 = bgroup1;
    }

    @Column(name="hiv1")
    public String getHiv1() {
        return this.hiv1;
    }

    public void setHiv1(String hiv1) {
        this.hiv1 = hiv1;
    }

    @Column(name="hcv1")
    public String getHcv1() {
        return this.hcv1;
    }

    public void setHcv1(String hcv1) {
        this.hcv1 = hcv1;
    }

    @Column(name="hbsag1")
    public String getHbsag1() {
        return this.hbsag1;
    }

    public void setHbsag1(String hbsag1) {
        this.hbsag1 = hbsag1;
    }

    @Column(name="vdrl1")
    public String getVdrl1() {
        return this.vdrl1;
    }

    public void setVdrl1(String vdrl1) {
        this.vdrl1 = vdrl1;
    }

    @Column(name="mp1")
    public String getMp1() {
        return this.mp1;
    }

    public void setMp1(String mp1) {
        this.mp1 = mp1;
    }

@Column(name="donors2")
    public String getDonors2() {
        return this.donors2;
    }

     public void setDonors2(String donors2) {
        this.donors2 = donors2;
    }

    @Column(name="bottleno2")
    public Long getBottleno2() {
        return this.bottleno2;
    }

    public void setBottleno2(Long bottleno2) {
        this.bottleno2 = bottleno2;
    }

    @Column(name="bgroup2", length=30)
    public String getBgroup2() {
        return this.bgroup2;
    }

    public void setBgroup2(String bgroup2) {
        this.bgroup2 = bgroup2;
    }

    @Column(name="hiv2")
    public String getHiv2() {
        return this.hiv2;
    }

    public void setHiv2(String hiv2) {
        this.hiv2 = hiv2;
    }

    @Column(name="hcv2")
    public String getHcv2() {
        return this.hcv2;
    }

    public void setHcv2(String hcv2) {
        this.hcv2 = hcv2;
    }

    @Column(name="hbsag2")
    public String getHbsag2() {
        return this.hbsag2;
    }

    public void setHbsag2(String hbsag2) {
        this.hbsag2 = hbsag2;
    }

    @Column(name="vdrl2")
    public String getVdrl2() {
        return this.vdrl2;
    }

    public void setVdrl2(String vdrl2) {
        this.vdrl2 = vdrl2;
    }

    @Column(name="mp2")
    public String getMp2() {
        return this.mp2;
    }

    public void setMp2(String mp2) {
        this.mp2 = mp2;
    }



    @Column(name="qualityofblood")
    public Long getQualityofblood() {
        return this.qualityofblood;
    }

    public void setQualityofblood(Long qualityofblood) {
        this.qualityofblood = qualityofblood;
    }

    @Column(name="ml")
    public String getMl() {
        return this.ml;
    }

    public void setMl(String ml) {
        this.ml = ml;
    }

    @Column(name="ml1")
    public String getMl1() {
        return this.ml1;
    }

    public void setMl1(String ml1) {
        this.ml1 = ml1;
    }

    @Column(name="ml2")
    public String getMl2() {
        return this.ml2;
    }

    public void setMl2(String ml2) {
        this.ml2 = ml2;
    }

    @Column(name="ml3")
    public String getMl3() {
        return this.ml3;
    }

    public void setMl3(String ml3) {
        this.ml3 = ml3;
    }

    @Column(name="sd")
    public String getSd() {
        return this.sd;
    }
    
    public void setSd(String sd) {
        this.sd = sd;
    }




}


