package com.model.biochemistry.dto;
// Generated 3 Jul, 2017 4:43:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Biochemistry generated by hbm2java
 */
@Entity
@Table(name="biochemistry"
    ,schema="public"
)
@SequenceGenerator(name = "biochemistry_seq", sequenceName = "biochemistry_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)

public class Biochemistry  implements java.io.Serializable {


     private long id;
     private String name;
     private Short age;
     private String sex;
     private Long cardno;
     private String referredby;
     private Long serialno;
     
    
     private String normalvalue1;
     private String normalvalue2;
     private String normalvalue3;
     private String normalvalue4;
     private String normalvalue5;
     private String normalvalue6;
     private String normalvalue7;
     private String normalvalue8;
     private String normalvalue9;
     private String remarks;
     private String labtech;
     private Date ddate;
    private String result1;
     private String result2;
      private String result3;
       private String result4;
        private String result5;
        private String result6;
          private String result7;
          private String result8;
          private String result9;
            private String result10;
             private String crp;
              private String ra;


    public Biochemistry() {
    }

	
    public Biochemistry(long id) {
        this.id = id;
    }
    public Biochemistry(long id, String name, Short age, String sex, Long cardno, String referredby, String crp, String ra, Long serialno, String result1, String result2, String result3, String result4, String result5, String result6, String result7, String result8, String result9, String result10, String normalvalue1, String normalvalue2, String normalvalue3, String normalvalue4, String normalvalue5, String normalvalue6, String normalvalue7, String normalvalue8, String normalvalue9, String remarks, String labtech, Date ddate) {
       this.id = id;
       this.name = name;
       this.age = age;
       this.sex = sex;
       this.cardno = cardno;
       this.referredby = referredby;
       this.serialno = serialno;
       
       this.result1 = result1;
       this.result2 = result2;
       this.result3 = result3;
       this.result4 = result4;
       this.result5 = result5;
       this.result6 = result6;
       this.result7 = result7;
       this.result8 = result8;
       this.result9 = result9;
       this.result10 = result10;
       this.normalvalue1 = normalvalue1;
       this.normalvalue1 = normalvalue2;
       this.normalvalue1 = normalvalue3;
       this.normalvalue1 = normalvalue4;
       this.normalvalue1 = normalvalue5;
       this.normalvalue6 = normalvalue6;
       this.normalvalue1 = normalvalue7;
       this.normalvalue1 = normalvalue8;
       this.normalvalue1 = normalvalue9;
       this.remarks = remarks;
       this.labtech = labtech;
       this.ddate=ddate;
       this.crp = crp;
       this.ra = ra;

    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
     @GeneratedValue(generator = "biochemistry_seq")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="name", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="age")
    public Short getAge() {
        return this.age;
    }
    
    public void setAge(Short age) {
        this.age = age;
    }
    
    @Column(name="sex", length=50)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    
    @Column(name = "cardno")
    public Long getCardno() {
        return cardno;
    }

    /**
     * @param cardno the cardno to set
     */
    public void setCardno(Long cardno) {
        this.cardno = cardno;
    }
    
    @Column(name="referredby", length=150)
    public String getReferredby() {
        return this.referredby;
    }
    
    public void setReferredby(String referredby) {
        this.referredby = referredby;
    }
    
    @Column(name="serialno")
    public Long getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Long serialno) {
        this.serialno = serialno;
    }
    
    


    @Column(name="result1")
    public String getResult1() {
        return this.result1;
    }

    public void setResult1(String result1) {
        this.result1 = result1;
    }

    @Column(name="result2")
    public String getResult2() {
        return this.result2;
    }

    public void setResult2(String result2) {
        this.result2 = result2;
    }

    @Column(name="result3")
    public String getResult3() {
        return this.result3;
    }

    public void setResult3(String result3) {
        this.result3 = result3;
    }

    @Column(name="result4")
    public String getResult4() {
        return this.result4;
    }

    public void setResult4(String result4) {
        this.result4 = result4;
    }

    @Column(name="result5")
    public String getResult5() {
        return this.result5;
    }

    public void setResult5(String result5) {
        this.result5 = result5;
    }

    @Column(name="result6")
    public String getResult6() {
        return this.result6;
    }

    public void setResult6(String result6) {
        this.result6 = result6;
    }

    @Column(name="result7")
    public String getResult7() {
        return this.result7;
    }

    public void setResult7(String result7) {
        this.result7 = result7;
    }

    @Column(name="result8")
    public String getResult8() {
        return this.result8;
    }

    public void setResult8(String result8) {
        this.result8 = result8;
    }

    @Column(name="result9")
    public String getResult9() {
        return this.result9;
    }

    public void setResult9(String result9) {
        this.result9 = result9;
    }

    @Column(name="result10")
    public String getResult10() {
        return this.result10;
    }

    public void setResult10(String result10) {
        this.result10 = result10;
    }
    
    
    @Column(name="normalvalue1")
    public String getNormalvalue1() {
        return this.normalvalue1;
    }
    
    public void setNormalvalue1(String normalvalue1) {
        this.normalvalue1 = normalvalue1;
    }
    @Column(name="normalvalue2")
    public String getNormalvalue2() {
        return this.normalvalue2;
    }

    public void setNormalvalue2(String normalvalue2) {
        this.normalvalue2 = normalvalue2;
    }
    @Column(name="normalvalue3")
    public String getNormalvalue3() {
        return this.normalvalue3;
    }

    public void setNormalvalue3(String normalvalue3) {
        this.normalvalue3 = normalvalue3;
    }
    @Column(name="normalvalue4")
    public String getNormalvalue4() {
        return this.normalvalue4;
    }

    public void setNormalvalue4(String normalvalue4) {
        this.normalvalue4 = normalvalue4;
    }
    @Column(name="normalvalue5")
    public String getNormalvalue5() {
        return this.normalvalue5;
    }

    public void setNormalvalue5(String normalvalue5) {
        this.normalvalue5 = normalvalue5;
    }
    
    @Column(name="normalvalue6")
    public String getNormalvalue6() {
        return this.normalvalue6;
    }
    
    public void setNormalvalue6(String normalvalue6) {
        this.normalvalue6 = normalvalue6;
    }
    @Column(name="normalvalue7")
    public String getNormalvalue7() {
        return this.normalvalue7;
    }

    public void setNormalvalue7(String normalvalue7) {
        this.normalvalue7 = normalvalue7;
    }
    @Column(name="normalvalue8")
    public String getNormalvalue8() {
        return this.normalvalue8;
    }

    public void setNormalvalue8(String normalvalue8) {
        this.normalvalue8 = normalvalue8;
    }
    @Column(name="normalvalue9")
    public String getNormalvalue9() {
        return this.normalvalue9;
    }

    public void setNormalvalue9(String normalvalue9) {
        this.normalvalue9 = normalvalue9;
    }
    
    @Column(name="remarks")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
    @Column(name="labtech", length=150)
    public String getLabtech() {
        return this.labtech;
    }
    
    public void setLabtech(String labtech) {
        this.labtech = labtech;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ddate", length=13)
    public Date getDdate() {
        return this.ddate;
    }

    public void setDdate(Date ddate) {
        this.ddate = ddate;
    }

 @Column(name="crp")
    public String getCrp() {
        return this.crp;
    }

    public void setCrp(String crp) {
        this.crp = crp;
    }

    @Column(name="ra")
    public String getRa() {
        return this.ra;
    }

    public void setRa(String ra) {
        this.ra = ra;
    }
}


