package com.model.prescription.dto;
// Generated Apr 9, 2012 4:49:32 PM by Hibernate Tools 3.2.1.GA

import com.model.dossage.dto.Dossage;
import com.model.visit.dto.Visit;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Prescription generated by hbm2java
 */
@Entity
@Table(name = "prescription", schema = "public")
@SequenceGenerator(name = "prescription_seq", sequenceName = "prescription_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Prescription implements java.io.Serializable {

    private long id;
    private Visit visit;
    private Set<Dossage> dossages = new HashSet<Dossage>(0);

    /**
     *
     */
    public Prescription() {
    }
    
    /**
     *
     * @return
     */
    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(generator = "prescription_seq")
    public long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "visitid", nullable = false)
    public Visit getVisit() {
        return this.visit;
    }

    /**
     *
     * @param visit
     */
    public void setVisit(Visit visit) {
        this.visit = visit;
    }

    /**
     *
     * @return
     */
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prescription")
    public Set<Dossage> getDossages() {
        return this.dossages;
    }

    /**
     *
     * @param dossages
     */
    public void setDossages(Set<Dossage> dossages) {
        this.dossages = dossages;
    }
}


