package com.model.operationType.dto;
// Generated 10 Sep, 2017 4:40:47 PM by Hibernate Tools 3.2.1.GA


import com.model.detailsOperationBill.dto.Detailsoperationbillchild;
import com.model.operationBill.dto.Operationbill;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Operationtype generated by hbm2java
 */
@Entity
@Table(name="operationtype"
    ,schema="public"
)
        @SequenceGenerator(name = "operationtype_seq", sequenceName = "operationtype_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Operationtype  implements java.io.Serializable {


     private long operationtypeid;
     private String operationtype;
     private BigDecimal operationtypecharge;
     private boolean usefull;
     private Set<Operationbill> operationbills = new HashSet<Operationbill>(0);
     private Set<Detailsoperationbillchild> detailsoperationbillchilds = new HashSet<Detailsoperationbillchild>(0);

    public Operationtype() {
    }


    public Operationtype(long operationtypeid, String operationtype, boolean usefull) {
        this.operationtypeid = operationtypeid;
        this.operationtype = operationtype;
        this.usefull = usefull;
    }
    public Operationtype(long operationtypeid, String operationtype, BigDecimal operationtypecharge, boolean usefull, Set<Operationbill> operationbills, Set<Detailsoperationbillchild> detailsoperationbillchilds) {
       this.operationtypeid = operationtypeid;
       this.operationtype = operationtype;
       this.operationtypecharge = operationtypecharge;
       this.usefull = usefull;
       this.operationbills = operationbills;
       this.detailsoperationbillchilds = detailsoperationbillchilds;
    }

     @Id

    @Column(name="operationtypeid", unique=true, nullable=false)
     @GeneratedValue(generator = "operationtype_seq")
    public long getOperationtypeid() {
        return this.operationtypeid;
    }

    public void setOperationtypeid(long operationtypeid) {
        this.operationtypeid = operationtypeid;
    }

    @Column(name="operationtype", nullable=false, length=1000)
    public String getOperationtype() {
        return this.operationtype;
    }

    public void setOperationtype(String operationtype) {
        this.operationtype = operationtype;
    }

    @Column(name="operationtypecharge", precision=20)
    public BigDecimal getOperationtypecharge() {
        return this.operationtypecharge;
    }

    public void setOperationtypecharge(BigDecimal operationtypecharge) {
        this.operationtypecharge = operationtypecharge;
    }

    @Column(name="usefull", nullable=false)
    public boolean isUsefull() {
        return this.usefull;
    }

    public void setUsefull(boolean usefull) {
        this.usefull = usefull;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="operationtype")
    public Set<Operationbill> getOperationbills() {
        return this.operationbills;
    }

    public void setOperationbills(Set<Operationbill> operationbills) {
        this.operationbills = operationbills;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="operationtype")
    public Set<Detailsoperationbillchild> getDetailsoperationbillchilds() {
        return this.detailsoperationbillchilds;
    }

    public void setDetailsoperationbillchilds(Set<Detailsoperationbillchild> detailsoperationbillchilds) {
        this.detailsoperationbillchilds = detailsoperationbillchilds;
    }




}


