package com.model.inreport.dto;
// Generated Jul 22, 2014 5:04:22 PM by Hibernate Tools 3.2.1.GA


import com.model.inPatient.dto.Inpatient;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inreport generated by hbm2java
 */
@Entity
@Table(name="inreport"
    ,schema="public"
)
         @SequenceGenerator(name = "inreport_seq", sequenceName = "inreport_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Inreport  implements java.io.Serializable {


     private long inreportid;
     private Inpatient inpatient;
     private String inreportname;
     private Date inreportdate;
     private String inremarks;
     private String inobservation;
     private String reportimage;
     private String emsting;
     private Long empty1;

    public Inreport() {
    }


    public Inreport(long inreportid, Inpatient inpatient) {
        this.inreportid = inreportid;
        this.inpatient = inpatient;
    }
    public Inreport(long inreportid, Inpatient inpatient, String inreportname, Date inreportdate, String inremarks, String inobservation, String reportimage, Long empty1, String emsting) {
       this.inreportid = inreportid;
       this.inpatient = inpatient;
       this.inreportname = inreportname;
       this.inreportdate = inreportdate;
       this.inremarks = inremarks;
       this.inobservation = inobservation;
       this.reportimage = reportimage;
       this.empty1 = empty1;
       this.emsting = emsting;
    }

     @Id

    @Column(name="inreportid", unique=true, nullable=false)
     @GeneratedValue(generator = "inreport_seq")
    public long getInreportid() {
        return this.inreportid;
    }

    public void setInreportid(long inreportid) {
        this.inreportid = inreportid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false)
    public Inpatient getInpatient() {
        return this.inpatient;
    }

    public void setInpatient(Inpatient inpatient) {
        this.inpatient = inpatient;
    }

    @Column(name="inreportname", length=300)
    public String getInreportname() {
        return this.inreportname;
    }

    public void setInreportname(String inreportname) {
        this.inreportname = inreportname;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="inreportdate", length=13)
    public Date getInreportdate() {
        return this.inreportdate;
    }

    public void setInreportdate(Date inreportdate) {
        this.inreportdate = inreportdate;
    }

    @Column(name="inremarks", length=1000)
    public String getInremarks() {
        return this.inremarks;
    }

    public void setInremarks(String inremarks) {
        this.inremarks = inremarks;
    }

    @Column(name="inobservation", length=1000)
    public String getInobservation() {
        return this.inobservation;
    }

    public void setInobservation(String inobservation) {
        this.inobservation = inobservation;
    }

    @Column(name="reportimage", length=100)
    public String getReportimage() {
        return this.reportimage;
    }

    public void setReportimage(String reportimage) {
        this.reportimage = reportimage;
    }

    @Column(name="emsting", length=1000)
    public String getEmsting() {
        return this.emsting;
    }

    public void setEmsting(String emsting) {
        this.emsting = emsting;
    }

    @Column(name="empty1")
    public Long getEmpty1() {
        return this.empty1;
    }

    public void setEmpty1(Long empty1) {
        this.empty1 = empty1;
    }




}


