package com.model.unitdispensedose.dto;
// Generated Aug 14, 2012 12:27:55 PM by Hibernate Tools 3.2.1.GA

import com.model.dispense.dto.Dispense;
import com.model.medicine.dto.Medicine;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Unitdispensedose generated by hbm2java
 */
@Entity
@Table(name = "unitdispensedose", schema = "public")
@SequenceGenerator(name = "unitdispensedose_seq", sequenceName = "unitdispensedose_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Unitdispensedose implements java.io.Serializable {

    private long id;
    private Medicine medicine;
    private Dispense dispense;
    private Long quantity;
    private BigDecimal amount;

    /**
     *
     */
    public Unitdispensedose() {
    }

    /**
     *
     * @return
     */
    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(generator = "unitdispensedose_seq")
    public long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medicineid", nullable = false)
    public Medicine getMedicine() {
        return this.medicine;
    }

    /**
     *
     * @param medicine
     */
    public void setMedicine(Medicine medicine) {
        this.medicine = medicine;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "dispenseid", nullable = false)
    public Dispense getDispense() {
        return this.dispense;
    }

    /**
     *
     * @param dispense
     */
    public void setDispense(Dispense dispense) {
        this.dispense = dispense;
    }

    /**
     *
     * @return
     */
    @Column(name = "quantity")
    public Long getQuantity() {
        return this.quantity;
    }

    /**
     *
     * @param quantity
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     *
     * @return
     */
    @Column(name = "amount", precision = 20)
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     *
     * @param amount
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}


