package com.model.consultancytype.dto;
// Generated Feb 18, 2016 12:33:15 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Consultancytype generated by hbm2java
 */
@Entity
@Table(name="consultancytype"
    ,schema="public"
)
        @SequenceGenerator(name = "consultancytype_seq", sequenceName = "consultancytype_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Consultancytype  implements java.io.Serializable {


     private long consultancyid;
     private String consultanttypename;
     private BigDecimal cntlcycharges;
     private boolean usefull;
     private String refferedby;
     private BigDecimal discount;
     private BigDecimal total;

    public Consultancytype() {
    }

	
    public Consultancytype(long consultancyid, boolean usefull) {
        this.consultancyid = consultancyid;
        this.usefull = usefull;
    }
    public Consultancytype(long consultancyid, String consultanttypename, BigDecimal cntlcycharges, boolean usefull) {
       this.consultancyid = consultancyid;
       this.consultanttypename = consultanttypename;
       this.cntlcycharges = cntlcycharges;
       this.usefull = usefull;
    }
   
     @Id 
    
    @Column(name="consultancyid", unique=true, nullable=false)
     @GeneratedValue(generator = "consultancytype_seq")
    public long getConsultancyid() {
        return this.consultancyid;
    }
    
    public void setConsultancyid(long consultancyid) {
        this.consultancyid = consultancyid;
    }
    
    @Column(name="consultanttypename", length=150)
    public String getConsultanttypename() {
        return this.consultanttypename;
    }
    
    public void setConsultanttypename(String consultanttypename) {
        this.consultanttypename = consultanttypename;
    }
    
    @Column(name="cntlcycharges", precision=20)
    public BigDecimal getCntlcycharges() {
        return this.cntlcycharges;
    }
    
    public void setCntlcycharges(BigDecimal cntlcycharges) {
        this.cntlcycharges = cntlcycharges;
    }
    
    @Column(name="usefull", nullable=false)
    public boolean isUsefull() {
        return this.usefull;
    }
    
    public void setUsefull(boolean usefull) {
        this.usefull = usefull;
    }

     @Column(name="refferedby", length=150)
    public String getrefferedby() {
        return this.refferedby;
    }

    public void setRefferedby(String refferedby) {
        this.refferedby = refferedby;
    }

     @Column(name="discount", precision=20)
    public BigDecimal getDiscount() {
        return this.discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    
    @Column(name="total", precision=20)
    public BigDecimal getTotal() {
        return this.total;
    }
    public void setTotal(BigDecimal total) {
        this.total = total;
    }




}


