package com.model.therapybill.dto;
// Generated Aug 4, 2014 3:43:41 PM by Hibernate Tools 3.2.1.GA


import com.model.bill.dto.Bill;
import com.model.detailTherapyBill.dto.Detailstherapybill;
import com.model.doctorProcess.dto.Doctorinfo;
import com.model.patient.dto.Patient;
import com.model.therapy.dto.Theraphy;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Therapybill generated by hbm2java
 */
@Entity
@Table(name="therapybill"
    ,schema="public"
)
        @SequenceGenerator(name = "therapybill_seq", sequenceName = "therapybill_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Therapybill  implements java.io.Serializable {


     private long therapybillid;
     private Patient patient;
     private Doctorinfo doctorinfo;
     private Bill bill;
     private Theraphy theraphy;
     private Date therapybilldate;
     private BigDecimal therapybillcharges;
     private String therapybillremark;
     private Set<Detailstherapybill> detailstherapybills = new HashSet<Detailstherapybill>(0);

    public Therapybill() {
    }

	
    public Therapybill(long therapybillid, Theraphy theraphy, Date therapybilldate) {
        this.therapybillid = therapybillid;
        this.theraphy = theraphy;
        this.therapybilldate = therapybilldate;
    }
    public Therapybill(long therapybillid, Patient patient, Doctorinfo doctorinfo, Theraphy theraphy, Date therapybilldate, BigDecimal therapybillcharges, String therapybillremark, Set<Detailstherapybill> detailstherapybills) {
       this.therapybillid = therapybillid;
       this.patient = patient;
       this.doctorinfo = doctorinfo;
       this.theraphy = theraphy;
       this.therapybilldate = therapybilldate;
       this.therapybillcharges = therapybillcharges;
       this.therapybillremark = therapybillremark;
       this.detailstherapybills = detailstherapybills;
    }
   
     @Id 
    
    @Column(name="therapybillid", unique=true, nullable=false)
     @GeneratedValue(generator = "therapybill_seq")
    public long getTherapybillid() {
        return this.therapybillid;
    }
    
    public void setTherapybillid(long therapybillid) {
        this.therapybillid = therapybillid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patientid")
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doctorid")
    public Doctorinfo getDoctorinfo() {
        return this.doctorinfo;
    }
    
    public void setDoctorinfo(Doctorinfo doctorinfo) {
        this.doctorinfo = doctorinfo;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="billid")
    public Bill getBill() {
        return this.bill;
    }

    public void setBill(Bill bill) {
        this.bill = bill;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="therapytypeid", nullable=true)
    public Theraphy getTheraphy() {
        return this.theraphy;
    }
    
    public void setTheraphy(Theraphy theraphy) {
        this.theraphy = theraphy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="therapybilldate", nullable=false, length=13)
    public Date getTherapybilldate() {
        return this.therapybilldate;
    }
    
    public void setTherapybilldate(Date therapybilldate) {
        this.therapybilldate = therapybilldate;
    }
    
    @Column(name="therapybillcharges", precision=20)
    public BigDecimal getTherapybillcharges() {
        return this.therapybillcharges;
    }
    
    public void setTherapybillcharges(BigDecimal therapybillcharges) {
        this.therapybillcharges = therapybillcharges;
    }
    
    @Column(name="therapybillremark", length=2000)
    public String getTherapybillremark() {
        return this.therapybillremark;
    }
    
    public void setTherapybillremark(String therapybillremark) {
        this.therapybillremark = therapybillremark;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="therapybill")
    public Set<Detailstherapybill> getDetailstherapybills() {
        return this.detailstherapybills;
    }

    public void setDetailstherapybills(Set<Detailstherapybill> detailstherapybills) {
        this.detailstherapybills = detailstherapybills;
    }




}


