package com.model.sonography.dto;
// Generated Jul 17, 2017 1:16:29 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sonography generated by hbm2java
 */
@Entity
@Table(name="sonography"
    ,schema="public"
)
public class Sonography  implements java.io.Serializable {


     private long id;
     private String name;
     private String diagnosis;
     private String cliniccalinvestigation;
     private String sonography;
     private String abdomen;
     private String kubp;
     private String pelvis;
     private String obst;
     private String neck;
     private String musculoskeletal;
     private String colordopplerstudy;
     private String bariam;
     private String ddate;
     private String sex;
     private String refbydr;

    public Sonography() {
    }

	
    public Sonography(long id) {
        this.id = id;
    }
    public Sonography(long id, String name, String diagnosis, String cliniccalinvestigation, String sonography, String abdomen, String kubp, String pelvis, String obst, String neck, String musculoskeletal, String colordopplerstudy, String bariam, String ddate, String sex, String refbydr) {
       this.id = id;
       this.name = name;
       this.diagnosis = diagnosis;
       this.cliniccalinvestigation = cliniccalinvestigation;
       this.sonography = sonography;
       this.abdomen = abdomen;
       this.kubp = kubp;
       this.pelvis = pelvis;
       this.obst = obst;
       this.neck = neck;
       this.musculoskeletal = musculoskeletal;
       this.colordopplerstudy = colordopplerstudy;
       this.bariam = bariam;
       this.ddate = ddate;
       this.sex = sex;
       this.refbydr = refbydr;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="name", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="diagnosis")
    public String getDiagnosis() {
        return this.diagnosis;
    }
    
    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }
    
    @Column(name="cliniccalinvestigation")
    public String getCliniccalinvestigation() {
        return this.cliniccalinvestigation;
    }
    
    public void setCliniccalinvestigation(String cliniccalinvestigation) {
        this.cliniccalinvestigation = cliniccalinvestigation;
    }
    
    @Column(name="sonography")
    public String getSonography() {
        return this.sonography;
    }
    
    public void setSonography(String sonography) {
        this.sonography = sonography;
    }
    
    @Column(name="abdomen")
    public String getAbdomen() {
        return this.abdomen;
    }
    
    public void setAbdomen(String abdomen) {
        this.abdomen = abdomen;
    }
    
    @Column(name="kubp")
    public String getKubp() {
        return this.kubp;
    }
    
    public void setKubp(String kubp) {
        this.kubp = kubp;
    }
    
    @Column(name="pelvis")
    public String getPelvis() {
        return this.pelvis;
    }
    
    public void setPelvis(String pelvis) {
        this.pelvis = pelvis;
    }
    
    @Column(name="obst")
    public String getObst() {
        return this.obst;
    }
    
    public void setObst(String obst) {
        this.obst = obst;
    }
    
    @Column(name="neck")
    public String getNeck() {
        return this.neck;
    }
    
    public void setNeck(String neck) {
        this.neck = neck;
    }
    
    @Column(name="musculoskeletal")
    public String getMusculoskeletal() {
        return this.musculoskeletal;
    }
    
    public void setMusculoskeletal(String musculoskeletal) {
        this.musculoskeletal = musculoskeletal;
    }
    
    @Column(name="colordopplerstudy")
    public String getColordopplerstudy() {
        return this.colordopplerstudy;
    }
    
    public void setColordopplerstudy(String colordopplerstudy) {
        this.colordopplerstudy = colordopplerstudy;
    }
    
    @Column(name="bariam")
    public String getBariam() {
        return this.bariam;
    }
    
    public void setBariam(String bariam) {
        this.bariam = bariam;
    }
    
    @Column(name="ddate")
    public String getDdate() {
        return this.ddate;
    }
    
    public void setDdate(String ddate) {
        this.ddate = ddate;
    }
    
    @Column(name="sex", length=10)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    
    @Column(name="refbydr", length=150)
    public String getRefbydr() {
        return this.refbydr;
    }
    
    public void setRefbydr(String refbydr) {
        this.refbydr = refbydr;
    }




}


