package com.model.detailTherapyBill.dto;
// Generated Sep 1, 2014 2:58:22 PM by Hibernate Tools 3.2.1.GA


import com.model.therapy.dto.Theraphy;
import com.model.therapybill.dto.Therapybill;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detailstherapybill generated by hbm2java
 */
@Entity
@Table(name="detailstherapybill"
    ,schema="public"
)
        @SequenceGenerator(name = "detailstherapybill_seq", sequenceName = "detailstherapybill_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Detailstherapybill  implements java.io.Serializable {


     private long detailstherapybillid;
     private Therapybill therapybill;
     private Theraphy theraphy;
     private Date detailstherapybilldate;
     private BigDecimal detailstherapybillcharge;

    public Detailstherapybill() {
    }

	
    public Detailstherapybill(long detailstherapybillid, Therapybill therapybill, Theraphy theraphy) {
        this.detailstherapybillid = detailstherapybillid;
        this.therapybill = therapybill;
        this.theraphy = theraphy;
    }
    public Detailstherapybill(long detailstherapybillid, Therapybill therapybill, Theraphy theraphy, Date detailstherapybilldate, BigDecimal detailstherapybillcharge) {
       this.detailstherapybillid = detailstherapybillid;
       this.therapybill = therapybill;
       this.theraphy = theraphy;
       this.detailstherapybilldate = detailstherapybilldate;
       this.detailstherapybillcharge = detailstherapybillcharge;
    }
   
     @Id 
    
    @Column(name="detailstherapybillid", unique=true, nullable=false)
     @GeneratedValue(generator = "detailstherapybill_seq")
    public long getDetailstherapybillid() {
        return this.detailstherapybillid;
    }
    
    public void setDetailstherapybillid(long detailstherapybillid) {
        this.detailstherapybillid = detailstherapybillid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="therapybillid", nullable=false)
    public Therapybill getTherapybill() {
        return this.therapybill;
    }
    
    public void setTherapybill(Therapybill therapybill) {
        this.therapybill = therapybill;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="therphyid", nullable=false)
    public Theraphy getTheraphy() {
        return this.theraphy;
    }
    
    public void setTheraphy(Theraphy theraphy) {
        this.theraphy = theraphy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="detailstherapybilldate", length=13)
    public Date getDetailstherapybilldate() {
        return this.detailstherapybilldate;
    }
    
    public void setDetailstherapybilldate(Date detailstherapybilldate) {
        this.detailstherapybilldate = detailstherapybilldate;
    }
    
    @Column(name="detailstherapybillcharge", precision=20)
    public BigDecimal getDetailstherapybillcharge() {
        return this.detailstherapybillcharge;
    }
    
    public void setDetailstherapybillcharge(BigDecimal detailstherapybillcharge) {
        this.detailstherapybillcharge = detailstherapybillcharge;
    }




}


