package com.model.RoomType.Dto;
// Generated Jul 5, 2016 3:45:38 PM by Hibernate Tools 3.2.1.GA


import com.model.roomndbedssetup.dto.Roomndbedsetup;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Roomtype generated by hbm2java
 */
@Entity
@Table(name="roomtype"
    ,schema="public"
)
        @SequenceGenerator(name = "room_seq", sequenceName = "room_seq")
         @org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Roomtype  implements java.io.Serializable {


     private long roomtypeid;
     private String roomcode;
     private String roomtype;
     private long roomcharges;
    private Set<Roomndbedsetup> roomndbedsetups = new HashSet<Roomndbedsetup>(0);

    public Roomtype() {
    }


    public Roomtype(long roomtypeid, String roomtype, long roomcharges) {
        this.roomtypeid = roomtypeid;
        this.roomtype = roomtype;
        this.roomcharges = roomcharges;
    }
    public Roomtype(long roomtypeid, String roomcode, String roomtype, long roomcharges, Set<Roomndbedsetup> roomndbedsetups) {
       this.roomtypeid = roomtypeid;
       this.roomcode = roomcode;
       this.roomtype = roomtype;
       this.roomcharges = roomcharges;
       this.roomndbedsetups = roomndbedsetups;
    }
   
     @Id 
    
    @Column(name="roomtypeid", unique=true, nullable=false)
     @GeneratedValue(generator = "room_seq")
    public long getRoomtypeid() {
        return this.roomtypeid;
    }
    
    public void setRoomtypeid(long roomtypeid) {
        this.roomtypeid = roomtypeid;
    }
    
    @Column(name="roomcode")
    public String getRoomcode() {
        return this.roomcode;
    }
    
    public void setRoomcode(String roomcode) {
        this.roomcode = roomcode;
    }
    
    @Column(name="roomtype", nullable=false)
    public String getRoomtype() {
        return this.roomtype;
    }
    
    public void setRoomtype(String roomtype) {
        this.roomtype = roomtype;
    }
    
    @Column(name="roomcharges", nullable=false)
    public long getRoomcharges() {
        return this.roomcharges;
    }
    
    public void setRoomcharges(long roomcharges) {
        this.roomcharges = roomcharges;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="roomtype")
    public Set<Roomndbedsetup> getRoomndbedsetups() {
        return this.roomndbedsetups;
    }

    public void setRoomndbedsetups(Set<Roomndbedsetup> roomndbedsetups) {
        this.roomndbedsetups = roomndbedsetups;
    }

   



}


