package com.model.inVisit.dto;
// Generated Mar 28, 2013 6:44:17 PM by Hibernate Tools 3.2.1.GA


import com.model.inPatient.dto.Inpatient;
import com.model.inbill.dto.Inbill;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;





import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;



import javax.persistence.OneToMany;


/**
 * Invisit generated by hbm2java
 */
@Entity
@Table(name="invisit"
    ,schema="public"
)
@SequenceGenerator(name = "invisit_seq", sequenceName = "invisit_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
@SuppressWarnings("serial")
public class Invisit  implements java.io.Serializable {


     private long id;
     private Inpatient inpatient;
     private Date remindertime;
     private Date visittime;
     private long patientrating;
     private String remarks;
     private Long pulse;
     private Long rr;
     private String diagnosis;
     private String investigation;
     private String treatment;
     private String presentcomplaint;
     private Boolean status;
     private String bp;
     private String finaldiagnosis;
      private String time;
      private String managementplan;
       private Long countid;
       private Set<Inbill> inbills = new HashSet<Inbill>(0);

    public Invisit() {
    }

	
    public Invisit(long id, Inpatient inpatient, Date remindertime, Date visittime, long patientrating) {
        this.id = id;
        this.inpatient = inpatient;
        this.remindertime = remindertime;
        this.visittime = visittime;
        this.patientrating = patientrating;
    }
    public Invisit(long id, Inpatient inpatient, Date remindertime, Date visittime, long patientrating, String remarks, Long pulse, Long rr, String diagnosis, String investigation, String treatment, String presentcomplaint, Boolean status, String bp, String finaldiagnosis, String time, Long countid,Set<Inbill> inbills) {
       this.id = id;
       this.inpatient = inpatient;
       this.remindertime = remindertime;
       this.visittime = visittime;
       this.patientrating = patientrating;
       this.remarks = remarks;
       this.pulse = pulse;
       this.rr = rr;
       this.diagnosis = diagnosis;
       this.investigation = investigation;
       this.treatment = treatment;
       this.presentcomplaint = presentcomplaint;
       this.status = status;
       this.bp = bp;
       this.finaldiagnosis = finaldiagnosis;
       this.inbills = inbills;
       this.time = time;
         this.countid = countid;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
      @GeneratedValue(generator = "invisit_seq")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inpatientid", nullable=false)
    public Inpatient getInpatient() {
        return this.inpatient;
    }
    
    public void setInpatient(Inpatient inpatient) {
        this.inpatient = inpatient;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="remindertime", length=29)
    public Date getRemindertime() {
        return this.remindertime;
    }
    
    public void setRemindertime(Date remindertime) {
        this.remindertime = remindertime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="visittime", length=29)
    public Date getVisittime() {
        return this.visittime;
    }
    
    public void setVisittime(Date visittime) {
        this.visittime = visittime;
    }
    
    @Column(name="patientrating")
    public long getPatientrating() {
        return this.patientrating;
    }
    
    public void setPatientrating(long patientrating) {
        this.patientrating = patientrating;
    }
    
    @Column(name="remarks")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
    @Column(name="pulse")
    public Long getPulse() {
        return this.pulse;
    }
    
    public void setPulse(Long pulse) {
        this.pulse = pulse;
    }



      @Column(name="managementplan")
    public String getManagementplan() {
        return this.managementplan;
    }

    public void setManagementplan(String managementplan) {
        this.managementplan = managementplan;
    }
    
    @Column(name="rr")
    public Long getRr() {
        return this.rr;
    }
    
    public void setRr(Long rr) {
        this.rr = rr;
    }
    
    @Column(name="diagnosis")
    public String getDiagnosis() {
        return this.diagnosis;
    }
    
    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }
    
    @Column(name="investigation")
    public String getInvestigation() {
        return this.investigation;
    }
    
    public void setInvestigation(String investigation) {
        this.investigation = investigation;
    }
    
    @Column(name="treatment")
    public String getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }
    
    @Column(name="presentcomplaint")
    public String getPresentcomplaint() {
        return this.presentcomplaint;
    }
    
    public void setPresentcomplaint(String presentcomplaint) {
        this.presentcomplaint = presentcomplaint;
    }
    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @Column(name="bp", length=10)
    public String getBp() {
        return this.bp;
    }
    
    public void setBp(String bp) {
        this.bp = bp;
    }
    
    @Column(name="finaldiagnosis", length=50)
    public String getFinaldiagnosis() {
        return this.finaldiagnosis;
    }
    
    public void setFinaldiagnosis(String finaldiagnosis) {
        this.finaldiagnosis = finaldiagnosis;
    }


    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="invisit")
    public Set<Inbill> getInbills() {
        return this.inbills;
    }

    public void setInbills(Set<Inbill> inbills) {
        this.inbills = inbills;
    }

 @Column(name="time", length=10)
    public String getTime() {
        return this.time;
    }

    public void setTime(String time) {
        this.time = time;
    }

      @Column(name="countid")
    public Long getCountid() {
        return this.countid;
    }

    public void setCountid(Long countid) {
        this.countid = countid;
    }


}


