package com.model.stock.dto;
// Generated Apr 9, 2012 3:37:52 PM by Hibernate Tools 3.2.1.GA
 
import com.model.medicine.dto.Medicine;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.dialect.PostgreSQLDialect;
/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", schema = "public")
@SequenceGenerator(name = "stock_seq", sequenceName = "stock_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
@SuppressWarnings("serial")
public class Stock extends PostgreSQLDialect implements java.io.Serializable {

    private long id;
    private Medicine medicine;
    private long availablestock;
    private Date creationdate;
    private Date expirydate;
    private Date manufacturedate;
    private String batchno;

    /**
     *
     */
    public Stock() {
        
    }

    /**
     *
     * @return
     */
    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(generator = "stock_seq")
    public long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medicineid", nullable = false)
    public Medicine getMedicine() {
        return this.medicine;
    }

    /**
     *
     * @param medicine
     */
    public void setMedicine(Medicine medicine) {
        this.medicine = medicine;
    }

    /**
     *
     * @return
     */
    @Column(name = "availablestock", nullable = false)
    public long getAvailablestock() {
        return this.availablestock;
    }

    /**
     *
     * @param availablestock
     */
    public void setAvailablestock(long availablestock) {
        this.availablestock = availablestock;
    }
    /**
     *
     * @return
     */
    @Column(name="batchno",nullable = false,length=20)
    public String getBatchno() {
        return batchno;
    }

    /**
     * @param batchno the batchno to set
     */
    public void setBatchno(String batchno) {
        this.batchno = batchno;
    }

    /**
     *
     * @return
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creationdate", nullable = false, length = 29)
    public Date getCreationdate() {
        return this.creationdate;
    }

    /**
     *
     * @param creationdate
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }
    /**
     *
     * @return
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "expirydate", length = 29)
    public Date getExpirydate() {
        return this.expirydate;
    }

    /**
     *
     * @param expirydate
     */
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    /**
     * @return the manufacturedate
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "manufacturedate", length = 29)
    public Date getManufacturedate() {
        return manufacturedate;
    }

    /**
     * @param manufacturedate the manufacturedate to set
     */
    public void setManufacturedate(Date manufacturedate) {
        this.manufacturedate = manufacturedate;
    }
}


