package com.model.dispense.dto;
// Generated Aug 14, 2012 12:27:55 PM by Hibernate Tools 3.2.1.GA

import com.model.unitdispensedose.dto.Unitdispensedose;
import com.model.dispensedmedicinebill.dto.Dispensedmedicinebill;
import com.model.medicine.dto.Medicine;
import com.model.patient.dto.Patient;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dispense generated by hbm2java
 */
@Entity
@Table(name = "dispense", schema = "public")
@SequenceGenerator(name = "dispense_seq", sequenceName = "dispense_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Dispense implements java.io.Serializable {

    private long id;
    private Patient patient;
    private Date dispensedate;
    private Set<Unitdispensedose> unitdispensedoses = new HashSet<Unitdispensedose>(0);
    private Set<Dispensedmedicinebill> dispensedmedicinebills = new HashSet<Dispensedmedicinebill>(0);
//    private Set<Medicine> medic = new HashSet<Medicine>(0);

    /**
     *
     */
    public Dispense() {
    }

    /**
     *
     * @return
     */
    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(generator = "dispense_seq")
    public long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "patientid", nullable = false)
    public Patient getPatient() {
        return this.patient;
    }

    /**
     *
     * @param patient
     */
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    /**
     *
     * @return
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dispensedate", length = 29)
    public Date getDispensedate() {
        return this.dispensedate;
    }

    /**
     *
     * @param dispensedate
     */
    public void setDispensedate(Date dispensedate) {
        this.dispensedate = dispensedate;
    }

    /**
     *
     * @return
     */
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dispense")
    public Set<Unitdispensedose> getUnitdispensedoses() {
        return this.unitdispensedoses;
    }

    /**
     *
     * @param unitdispensedoses
     */
    public void setUnitdispensedoses(Set<Unitdispensedose> unitdispensedoses) {
        this.unitdispensedoses = unitdispensedoses;
    }

    /**
     *
     * @return
     */
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dispense")
    public Set<Dispensedmedicinebill> getDispensedmedicinebills() {
        return this.dispensedmedicinebills;
    }

    /**
     *
     * @param dispensedmedicinebills
     */
    public void setDispensedmedicinebills(Set<Dispensedmedicinebill> dispensedmedicinebills) {
        this.dispensedmedicinebills = dispensedmedicinebills;
    }

//    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dispense")
//    public Set<Medicine> getMedic() {
//        return this.medic;
//    }
//
//    /**
//     *
//     * @param dispensedmedicinebills
//     */
//    public void setMedic(Set<Medicine> medic) {
//        this.medic = medic;
//    }
}


