package com.model.dossage.dto;
// Generated Apr 9, 2012 4:49:32 PM by Hibernate Tools 3.2.1.GA
 
import com.model.prescription.dto.Prescription;
import com.model.medicine.dto.Medicine;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
 
/**
 * Dossage generated by hbm2java
 */
@Entity
@Table(name = "dossage", schema = "public")
@SequenceGenerator(name = "dossage_seq", sequenceName = "dossage_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Dossage implements java.io.Serializable {

    private long id;
    private Medicine medicine;
    private Prescription prescription;
    private String dosing;
    private String duration;
    private String remarks;

    /**
     *
     */
    public Dossage() {
    }

    /**
     *
     * @return
     */
    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(generator = "dossage_seq")
    public long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medicineid", nullable = false)
    public Medicine getMedicine() {
        return this.medicine;
    }

    /**
     *
     * @param medicine
     */
    public void setMedicine(Medicine medicine) {
        this.medicine = medicine;
    }

    /**
     *
     * @return
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prescriptionid", nullable = false)
    public Prescription getPrescription() {
        return this.prescription;
    }

    /**
     *
     * @param prescription
     */
    public void setPrescription(Prescription prescription) {
        this.prescription = prescription;
    }

    /**
     *
     * @return
     */
    @Column(name = "dosing")
    public String getDosing() {
        return this.dosing;
    }

    /**
     *
     * @param dosing
     */
    public void setDosing(String dosing) {
        this.dosing = dosing;
    }

    /**
     *
     * @return
     */
    @Column(name = "duration", length = 50)
    public String getDuration() {
        return this.duration;
    }

    /**
     *
     * @param duration
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     *
     * @return
     */
    @Column(name = "remarks")
    public String getRemarks() {
        return this.remarks;
    }

    /**
     *
     * @param remarks
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}


