package com.model.gst.dto;
// Generated Jul 17, 2017 1:12:52 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Gst generated by hbm2java
 */
@Entity
@Table(name="gst"
    ,schema="public"
)
 @SequenceGenerator(name = "gst_seq", sequenceName = "gst_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Gst  implements java.io.Serializable {


     private long id;


     private String patient;
     private Long cardno;
     private String referredby;
      private String ddate;
      private String invoice;

     private String items;
     private String mdate;
     private String edate;
     private String batchno;
     private BigDecimal qlty;
     private BigDecimal addcgst;
     private BigDecimal addsgst;
     private BigDecimal addigst;
     private BigDecimal rate;
     private BigDecimal amount;
     

     private BigDecimal subtotal;
     private BigDecimal sgst;
     private BigDecimal cgst;
     private BigDecimal igst;
     private BigDecimal roundoff;
     private BigDecimal gsttotal;
     private BigDecimal grandtotal;




    public Gst() {
    }

	
    public Gst(long id) {
        this.id = id;
    }
    public Gst(long id, String patient, Long cardno, String referredby, String ddate, String invoice, String items, BigDecimal subtotal, BigDecimal sgst, BigDecimal cgst, BigDecimal igst, BigDecimal roundoff, BigDecimal gsttotal, BigDecimal grandtotal, String mdate, String edate, String batchno, BigDecimal qlty, BigDecimal addcgst, BigDecimal addsgst, BigDecimal addigst, BigDecimal rate, BigDecimal amount) {
       this.id = id;
       
       this.patient = patient;
       this.cardno = cardno;
       this.referredby = referredby;
       this.ddate = ddate;
       this.invoice = invoice;


       this.subtotal = subtotal;
       this.sgst = sgst;
       this.igst = igst;
       this.cgst = cgst;
       this.roundoff = roundoff;
       this.gsttotal = gsttotal;
       this.grandtotal = grandtotal;

       this.qlty = qlty;
       this.addcgst = addcgst;
       this.addsgst = addsgst;
       this.addigst = addigst;
       this.rate = rate;
       this.amount = amount;
       this.items = items;
       this.mdate = mdate;
       this.edate = edate;
       this.batchno = batchno;
    }
   
     @Id
    
    @GeneratedValue(generator = "gst_seq")
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Column(name="patient", length=150)
    public String getPatient() {
        return this.patient;
    }

    public void setPatient(String patient) {
        this.patient = patient;
    }

    @Column(name="cardno")
    public Long getCardno() {
        return this.cardno;
    }

    public void setCardno(Long cardno) {
        this.cardno = cardno;
    }


    @Column(name="referredby", length=150)
    public String getReferredby() {
        return this.referredby;
    }

    public void setReferredby(String referredby) {
        this.referredby = referredby;
    }


    @Column(name="ddate")
    public String getDdate() {
        return this.ddate;
    }

    public void setDdate(String ddate) {
        this.ddate = ddate;
    }


    @Column(name="invoice")
    public String getInvoice() {
        return this.invoice;
    }

    public void setInvoice(String invoice) {
        this.invoice = invoice;
    }



    @Column(name="qlty", precision=10)
    public BigDecimal getQlty() {
        return this.qlty;
    }
    
    public void setQlty(BigDecimal qlty) {
        this.qlty = qlty;
    }
    
    @Column(name="addcgst", precision=10)
    public BigDecimal getAddcgst() {
        return this.addcgst;
    }
    
    public void setAddcgst(BigDecimal addcgst) {
        this.addcgst = addcgst;
    }
    
    @Column(name="addsgst", precision=10)
    public BigDecimal getAddsgst() {
        return this.addsgst;
    }
    
    public void setAddsgst(BigDecimal addsgst) {
        this.addsgst = addsgst;
    }
    
    @Column(name="addigst", precision=10)
    public BigDecimal getAddigst() {
        return this.addigst;
    }
    
    public void setAddigst(BigDecimal addigst) {
        this.addigst = addigst;
    }
    
    @Column(name="rate", precision=10)
    public BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }
    
    @Column(name="amount", precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    
      @Column(name="items", length=50)
    public String getItems() {
        return this.items;
    }

    public void setItems(String items) {
        this.items = items;
    }
     @Column(name="mdate")
    public String getMdate() {
        return this.mdate;
    }

    public void setMdate(String mdate) {
        this.mdate = mdate;
    }
     @Column(name="edate")
    public String getEdate() {
        return this.edate;
    }

    public void setEdate(String edate) {
        this.edate = edate;
    }


     @Column(name="batchno")
    public String getBatchno() {
        return this.batchno;
    }

    public void setBatchno(String batchno) {
        this.batchno = batchno;
    }

    @Column(name="subtotal", precision=10)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }

    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }


    @Column(name="sgst", precision=10)
    public BigDecimal getSgst() {
        return this.sgst;
    }

    public void setSgst(BigDecimal sgst) {
        this.sgst = sgst;
    }

    @Column(name="cgst", precision=10)
    public BigDecimal getCgst() {
        return this.cgst;
    }

    public void setCgst(BigDecimal cgst) {
        this.cgst = cgst;
    }


    @Column(name="igst", precision=10)
    public BigDecimal getIgst() {
        return this.igst;
    }

    public void setIgst(BigDecimal igst) {
        this.igst = igst;
    }
    @Column(name="roundoff", precision=10)
    public BigDecimal getRoundoff() {
        return this.roundoff;
    }

    public void setRoundoff(BigDecimal roundoff) {
        this.roundoff = roundoff;
    }

    @Column(name="gsttotal", precision=10)
    public BigDecimal getGsttotal() {
        return this.gsttotal;
    }

    public void setGsttotal(BigDecimal gsttotal) {
        this.gsttotal = gsttotal;
    }

     @Column(name="grandtotal", precision=10)
    public BigDecimal getGrandtotal() {
        return this.grandtotal;
    }

    public void setGrandtotal(BigDecimal grandtotal) {
        this.grandtotal = grandtotal;
    }


}


