package com.model.report.dto;
// Generated Jul 17, 2014 1:29:50 PM by Hibernate Tools 3.2.1.GA


import com.model.patient.dto.Patient;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name="report"
    ,schema="public"
)
        @SequenceGenerator(name = "report_seq", sequenceName = "report_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Report  implements java.io.Serializable {


     private long reportid;
     private Patient patient;
     private String reportname;
     private Date reportdate;
     private String remarks;
     private String observation;
     private String epmty;
     private Long empty1;

    public Report() {
    }

	
    public Report(long reportid, Patient patient) {
        this.reportid = reportid;
        this.patient = patient;
    }
    public Report(long reportid, Patient patient, String reportname, Date reportdate, String remarks, String observation, String epmty, Long empty1) {
       this.reportid = reportid;
       this.patient = patient;
       this.reportname = reportname;
       this.reportdate = reportdate;
       this.remarks = remarks;
       this.observation = observation;
       this.epmty = epmty;
       this.empty1 = empty1;
    }
   
     @Id 
    
    @Column(name="reportid", unique=true, nullable=false)
     @GeneratedValue(generator = "report_seq")
    public long getReportid() {
        return this.reportid;
    }
    
    public void setReportid(long reportid) {
        this.reportid = reportid;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false)
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    
    @Column(name="reportname", length=300)
    public String getReportname() {
        return this.reportname;
    }
    
    public void setReportname(String reportname) {
        this.reportname = reportname;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="reportdate", length=13)
    public Date getReportdate() {
        return this.reportdate;
    }
    
    public void setReportdate(Date reportdate) {
        this.reportdate = reportdate;
    }
    
    @Column(name="remarks", length=1000)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    
    @Column(name="observation", length=1000)
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }
    
    @Column(name="epmty", length=1000)
    public String getEpmty() {
        return this.epmty;
    }
    
    public void setEpmty(String epmty) {
        this.epmty = epmty;
    }
    
    @Column(name="empty1")
    public Long getEmpty1() {
        return this.empty1;
    }
    
    public void setEmpty1(Long empty1) {
        this.empty1 = empty1;
    }




}


