package com.model.advance.dtochild;
// Generated 3 Sep, 2017 3:40:46 PM by Hibernate Tools 3.2.1.GA


import com.model.advance.dto.Advance;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Advancechildbill generated by hbm2java
 */
@Entity
@Table(name="advancechildbill"
    ,schema="public"
)
        @SequenceGenerator(name = "advancechild_seq", sequenceName = "advancechild_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Advancechildbill  implements java.io.Serializable {


     private long advancechildbillid;
     private Advance advance;
     private Date advancebilldate;
     private BigDecimal advanceamountchild;
     private BigDecimal totalbillchild;
     private BigDecimal paidchild;
     private BigDecimal remainingchildamount;

    public Advancechildbill() {
    }

	
    public Advancechildbill(long advancechildbillid, Advance advance, Date advancebilldate) {
        this.advancechildbillid = advancechildbillid;
        this.advance = advance;
        this.advancebilldate = advancebilldate;
    }
    public Advancechildbill(long advancechildbillid, Advance advance, Date advancebilldate, BigDecimal advanceamountchild, BigDecimal totalbillchild, BigDecimal paidchild, BigDecimal remainingchildamount) {
       this.advancechildbillid = advancechildbillid;
       this.advance = advance;
       this.advancebilldate = advancebilldate;
       this.advanceamountchild = advanceamountchild;
       this.totalbillchild = totalbillchild;
       this.paidchild = paidchild;
       this.remainingchildamount = remainingchildamount;
    }
   
     @Id 
    
    @Column(name="advancechildbillid", unique=true, nullable=false)
     @GeneratedValue(generator = "advancechild_seq")
    public long getAdvancechildbillid() {
        return this.advancechildbillid;
    }
    
    public void setAdvancechildbillid(long advancechildbillid) {
        this.advancechildbillid = advancechildbillid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="advancebillid", nullable=false)
    public Advance getAdvance() {
        return this.advance;
    }
    
    public void setAdvance(Advance advance) {
        this.advance = advance;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="advancebilldate", nullable=false, length=13)
    public Date getAdvancebilldate() {
        return this.advancebilldate;
    }
    
    public void setAdvancebilldate(Date advancebilldate) {
        this.advancebilldate = advancebilldate;
    }
    
    @Column(name="advanceamountchild", precision=20)
    public BigDecimal getAdvanceamountchild() {
        return this.advanceamountchild;
    }
    
    public void setAdvanceamountchild(BigDecimal advanceamountchild) {
        this.advanceamountchild = advanceamountchild;
    }
    
    @Column(name="totalbillchild", precision=20)
    public BigDecimal getTotalbillchild() {
        return this.totalbillchild;
    }
    
    public void setTotalbillchild(BigDecimal totalbillchild) {
        this.totalbillchild = totalbillchild;
    }
    
    @Column(name="paidchild", precision=20)
    public BigDecimal getPaidchild() {
        return this.paidchild;
    }
    
    public void setPaidchild(BigDecimal paidchild) {
        this.paidchild = paidchild;
    }
    
    @Column(name="remainingchildamount", precision=20)
    public BigDecimal getRemainingchildamount() {
        return this.remainingchildamount;
    }
    
    public void setRemainingchildamount(BigDecimal remainingchildamount) {
        this.remainingchildamount = remainingchildamount;
    }




}


