package com.model.inPatient.dto;
// Generated Mar 28, 2013 1:33:44 PM by Hibernate Tools 3.2.1.GA

import com.model.inVisit.dto.Invisit;
import com.model.indispense.dto.Indispense;
import com.model.inreport.dto.Inreport;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;

import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inpatient generated by hbm2java
 */
@Entity
@Table(name = "inpatient", schema = "public")
@SequenceGenerator(name = "inpatient_seq", sequenceName = "inpatient_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Inpatient implements java.io.Serializable {

    private long id;
    private Short age;
    private String nationality;
    private String historyofpresentillness;
    private String pasthistory;
    private String familyhistory;
    private String personalhistory;
    private String drugallergies;
    private Long regno;
    private String name;
    private Long telephoneno;
    private String sex;
    private String chiefcomplaints;
    private String married;
    private String refferedby;
    private String bloodgroup;
    private String address;
    private Long cardno;
    private Long adharcardno;
    private Date admitdate;
    private Date dischargedate;
    private String concludinghistory;
    private String followup;

    private String surname;
    private String sdwof;
    private String contactperson;
    private String village;
    private String tehsil;
    private String dist;
    private Long pincode;
    private Long mobilno;
    private String sdw;

    private Set<Inreport> inreports = new HashSet<Inreport>(0);
    private Set<Invisit> invisits = new HashSet<Invisit>(0);
    private Set<Indispense> indispenses = new HashSet<Indispense>(0);

    public Inpatient() {
    }

    public Inpatient(long id, long cardno, Date admitdate) {
        this.id = id;
        this.id = id;
        this.cardno = cardno;
        this.admitdate = admitdate;
    }

    public Inpatient(long id, String surname, String contactperson, String sdwof,  String sdw, Long pincode,  Long mobilno,String dist, String tehsil, String village,Short age, String nationality, String historyofpresentillness, String pasthistory, String familyhistory, String personalhistory, String drugallergies, Long regno, String name, Long telephoneno, String sex, String chiefcomplaints, String married, String refferedby, String bloodgroup, String address, Long cardno, Long adharcardno, Date admitdate, Date dischargedate, String concludinghistory, String followup, Set<Inreport> inreports) {
        this.id = id;
        this.age = age;
        this.nationality = nationality;
        this.historyofpresentillness = historyofpresentillness;
        this.pasthistory = pasthistory;
        this.familyhistory = familyhistory;
        this.personalhistory = personalhistory;
        this.drugallergies = drugallergies;
        this.regno = regno;
        this.name = name;
        this.telephoneno = telephoneno;
        this.sex = sex;
        this.chiefcomplaints = chiefcomplaints;
        this.married = married;
        this.refferedby = refferedby;
        this.bloodgroup = bloodgroup;
        this.address = address;
        this.cardno = cardno;
        this.adharcardno = adharcardno;
        this.admitdate = admitdate;
        this.dischargedate = dischargedate;
           this.concludinghistory = concludinghistory;

       this.followup = followup;
       this.inreports = inreports;

       this.surname = surname;
       this.contactperson = contactperson;
       this.sdwof = sdwof;
       this.dist = dist;
       this.tehsil = tehsil;
       this.village = village;
       this.mobilno = mobilno;
       this.pincode = pincode;
       this.sdw = sdw;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(generator = "inpatient_seq")
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "age")
    public Short getAge() {
        return this.age;
    }

    public void setAge(Short age) {
        this.age = age;
    }

    @Column(name = "nationality", length = 50)
    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    @Column(name = "historyofpresentillness")
    public String getHistoryofpresentillness() {
        return this.historyofpresentillness;
    }

    public void setHistoryofpresentillness(String historyofpresentillness) {
        this.historyofpresentillness = historyofpresentillness;
    }

    @Column(name = "pasthistory")
    public String getPasthistory() {
        return this.pasthistory;
    }

    public void setPasthistory(String pasthistory) {
        this.pasthistory = pasthistory;
    }

    @Column(name = "familyhistory")
    public String getFamilyhistory() {
        return this.familyhistory;
    }

    public void setFamilyhistory(String familyhistory) {
        this.familyhistory = familyhistory;
    }

    @Column(name = "personalhistory")
    public String getPersonalhistory() {
        return this.personalhistory;
    }

    public void setPersonalhistory(String personalhistory) {
        this.personalhistory = personalhistory;
    }

    @Column(name = "drugallergies")
    public String getDrugallergies() {
        return this.drugallergies;
    }

    public void setDrugallergies(String drugallergies) {
        this.drugallergies = drugallergies;
    }

    @Column(name = "regno")
    public Long getRegno() {
        return this.regno;
    }

    public void setRegno(Long regno) {
        this.regno = regno;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "telephoneno")
    public Long getTelephoneno() {
        return this.telephoneno;
    }

    public void setTelephoneno(Long telephoneno) {
        this.telephoneno = telephoneno;
    }

    @Column(name = "sex", length = 10)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name = "chiefcomplaints")
    public String getChiefcomplaints() {
        return this.chiefcomplaints;
    }

    public void setChiefcomplaints(String chiefcomplaints) {
        this.chiefcomplaints = chiefcomplaints;
    }

    @Column(name = "married", length = 10)
    public String getMarried() {
        return this.married;
    }

    public void setMarried(String married) {
        this.married = married;
    }

    @Column(name = "refferedby", length = 50)
    public String getRefferedby() {
        return this.refferedby;
    }

    public void setRefferedby(String refferedby) {
        this.refferedby = refferedby;
    }

    @Column(name = "bloodgroup", length = 30)
    public String getBloodgroup() {
        return this.bloodgroup;
    }

    public void setBloodgroup(String bloodgroup) {
        this.bloodgroup = bloodgroup;
    }

    @Column(name = "address", length = 200)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "cardno")
    public Long getCardno() {
        return this.cardno;
    }

    public void setCardno(Long cardno) {
        this.cardno = cardno;
    }

    @Column(name = "adharcardno")
    public Long getAdharcardno() {
        return this.adharcardno;
    }

    public void setAdharcardno(Long adharcardno) {
        this.adharcardno = adharcardno;
    }


    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "inpatient")
    public Set<Invisit> getInvisits() {
        return this.invisits;
    }

    public void setInvisits(Set<Invisit> invisits) {
        this.invisits = invisits;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "inpatient")
    public Set<Indispense> getIndispenses() {
        return this.indispenses;
    }

    public void setIndispenses(Set<Indispense> indispenses) {
        this.indispenses = indispenses;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "admitdate", nullable = false, length = 29)
    public Date getAdmitdate() {
        return this.admitdate;
    }

    public void setAdmitdate(Date admitdate) {
        this.admitdate = admitdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dischargedate", length = 29)
    public Date getDischargedate() {
        return this.dischargedate;
    }

    public void setDischargedate(Date dischargedate) {
        this.dischargedate = dischargedate;
    }


       @Column(name="concludinghistory")
    public String getConcludinghistory() {
        return this.concludinghistory;
    }

    public void setConcludinghistory(String concludinghistory) {
        this.concludinghistory = concludinghistory;
    }

    @Column(name="followup")
    public String getFollowup() {
        return this.followup;
    }

    public void setFollowup(String followup) {
        this.followup = followup;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="inpatient")
    public Set<Inreport> getInreports() {
        return this.inreports;
    }

    public void setInreports(Set<Inreport> inreports) {
        this.inreports = inreports;
    }

    @Column(name = "surname", length = 50)
    public String getSurname() {
        return this.surname;
    }

    /**
     *
     * @param name
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
     @Column(name = "sdwof", length = 150)
    public String getSdwof() {
        return this.sdwof;
    }

    /**
     *
     * @param name
     */
    public void setSdwof(String sdwof) {
        this.sdwof = sdwof;
    }

    @Column(name = "contactperson", length = 150)
    public String getContactperson() {
        return this.contactperson;
    }

    /**
     *
     * @param name
     */
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson;
    }


    @Column(name = "village")
    public String getVillage() {
        return this.village;
    }

    /**
     *
     * @param chiefcomplaints
     */
    public void setVillage(String village) {
        this.village = village;
    }

    @Column(name = "tehsil")
    public String getTehsil() {
        return this.tehsil;
    }

    /**
     *
     * @param chiefcomplaints
     */
    public void setTehsil(String tehsil) {
        this.tehsil = tehsil;
    }

    @Column(name = "dist")
    public String getDist() {
        return this.dist;
    }

    /**
     *
     * @param chiefcomplaints
     */
    public void setDist(String dist) {
        this.dist = dist;
    }

@Column(name = "pincode")
    public Long getPincode() {
        return pincode;
    }

    /**
     * @param cardno the cardno to set
     */
    public void setPincode(Long pincode) {
        this.pincode = pincode;
    }

@Column(name = "mobilno")
    public Long getMobilno() {
        return mobilno;
    }

    /**
     * @param cardno the cardno to set
     */
    public void setMobilno(Long mobilno) {
        this.mobilno = mobilno;
    }

    @Column(name = "sdw", length = 150)
    public String getSdw() {
        return this.sdw;
    }

    /**
     *
     * @param name
     */
    public void setSdw(String sdw) {
        this.sdw = sdw;
    }

}


