package com.model.licenceInfo.dto;
// Generated May 19, 2014 5:56:50 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Licenceinfo generated by hbm2java
 */
@Entity
@Table(name="licenceinfo"
    ,schema="public"
)
        //@SequenceGenerator(name = "licenceinfo_seq", sequenceName = "licenceinfo_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Licenceinfo  implements java.io.Serializable {


     private long licenceid;
     private String clientname;
     private String addressline1;
     private String addressline2;
     private String addressline3;
     private String addressline4;
     private String chiefmdname;
     private Long cmdcontno;
     private String cmdemailid;
     private Long cmdmobno;
     private String emailid;
     private String webaddress;
     private String logo1;
     private String logo2;

    public Licenceinfo() {
    }

	
    public Licenceinfo(long licenceid) {
        this.licenceid = licenceid;
    }
    public Licenceinfo(long licenceid, String clientname, String addressline1, String addressline2, String addressline3, String addressline4, String chiefmdname, Long cmdcontno, String cmdemailid, Long cmdmobno, String emailid, String webaddress, String logo1, String logo2) {
       this.licenceid = licenceid;
       this.clientname = clientname;
       this.addressline1 = addressline1;
       this.addressline2 = addressline2;
       this.addressline3 = addressline3;
       this.addressline4 = addressline4;
       this.chiefmdname = chiefmdname;
       this.cmdcontno = cmdcontno;
       this.cmdemailid = cmdemailid;
       this.cmdmobno = cmdmobno;
       this.emailid = emailid;
       this.webaddress = webaddress;
       this.logo1 = logo1;
       this.logo2 = logo2;
    }
   
     @Id 
    
    @Column(name="licenceid", unique=true, nullable=false)
     //@GeneratedValue(generator = "licenceinfo_seq")
    public long getLicenceid() {
        return this.licenceid;
    }
    
    public void setLicenceid(long licenceid) {
        this.licenceid = licenceid;
    }
    
    @Column(name="clientname", length=500)
    public String getClientname() {
        return this.clientname;
    }
    
    public void setClientname(String clientname) {
        this.clientname = clientname;
    }
    
    @Column(name="addressline1", length=200)
    public String getAddressline1() {
        return this.addressline1;
    }
    
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }
    
    @Column(name="addressline2", length=200)
    public String getAddressline2() {
        return this.addressline2;
    }
    
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }
    
    @Column(name="addressline3", length=200)
    public String getAddressline3() {
        return this.addressline3;
    }
    
    public void setAddressline3(String addressline3) {
        this.addressline3 = addressline3;
    }
    
    @Column(name="addressline4", length=200)
    public String getAddressline4() {
        return this.addressline4;
    }
    
    public void setAddressline4(String addressline4) {
        this.addressline4 = addressline4;
    }
    
    @Column(name="chiefmdname", length=200)
    public String getChiefmdname() {
        return this.chiefmdname;
    }
    
    public void setChiefmdname(String chiefmdname) {
        this.chiefmdname = chiefmdname;
    }
    
    @Column(name="cmdcontno")
    public Long getCmdcontno() {
        return this.cmdcontno;
    }
    
    public void setCmdcontno(Long cmdcontno) {
        this.cmdcontno = cmdcontno;
    }
    
    @Column(name="cmdemailid", length=150)
    public String getCmdemailid() {
        return this.cmdemailid;
    }
    
    public void setCmdemailid(String cmdemailid) {
        this.cmdemailid = cmdemailid;
    }
    
    @Column(name="cmdmobno")
    public Long getCmdmobno() {
        return this.cmdmobno;
    }
    
    public void setCmdmobno(Long cmdmobno) {
        this.cmdmobno = cmdmobno;
    }
    
    @Column(name="emailid", length=150)
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    
    @Column(name="webaddress", length=100)
    public String getWebaddress() {
        return this.webaddress;
    }
    
    public void setWebaddress(String webaddress) {
        this.webaddress = webaddress;
    }
    
    @Column(name="logo1", length=100)
    public String getLogo1() {
        return this.logo1;
    }
    
    public void setLogo1(String logo1) {
        this.logo1 = logo1;
    }
    
    @Column(name="logo2", length=100)
    public String getLogo2() {
        return this.logo2;
    }
    
    public void setLogo2(String logo2) {
        this.logo2 = logo2;
    }




}


