package com.model.xray.dto;
// Generated Jul 17, 2017 1:17:14 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Xray generated by hbm2java
 */
@Entity
@Table(name="xray"
    ,schema="public"
)
public class Xray  implements java.io.Serializable {


     private long id;
     private String name;
     private Short age;
     private String diagnosis;
     private String investigation;
     private String chest;
     private String kub;
     private String abdstanding;
     private String spine;
     private String pns;
     private String skullap;
     private String mastoids;
     private String date;
     private String sex;
     private String refbydr;

    public Xray() {
    }

	
    public Xray(long id) {
        this.id = id;
    }
    public Xray(long id, String name, Short age, String diagnosis, String investigation, String chest, String kub, String abdstanding, String spine, String pns, String skullap, String mastoids, String date, String sex, String refbydr) {
       this.id = id;
       this.name = name;
       this.age = age;
       this.diagnosis = diagnosis;
       this.investigation = investigation;
       this.chest = chest;
       this.kub = kub;
       this.abdstanding = abdstanding;
       this.spine = spine;
       this.pns = pns;
       this.skullap = skullap;
       this.mastoids = mastoids;
       this.date = date;
       this.sex = sex;
       this.refbydr = refbydr;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="name", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="age")
    public Short getAge() {
        return this.age;
    }
    
    public void setAge(Short age) {
        this.age = age;
    }
    
    @Column(name="diagnosis")
    public String getDiagnosis() {
        return this.diagnosis;
    }
    
    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }
    
    @Column(name="investigation")
    public String getInvestigation() {
        return this.investigation;
    }
    
    public void setInvestigation(String investigation) {
        this.investigation = investigation;
    }
    
    @Column(name="chest")
    public String getChest() {
        return this.chest;
    }
    
    public void setChest(String chest) {
        this.chest = chest;
    }
    
    @Column(name="kub")
    public String getKub() {
        return this.kub;
    }
    
    public void setKub(String kub) {
        this.kub = kub;
    }
    
    @Column(name="abdstanding")
    public String getAbdstanding() {
        return this.abdstanding;
    }
    
    public void setAbdstanding(String abdstanding) {
        this.abdstanding = abdstanding;
    }
    
    @Column(name="spine")
    public String getSpine() {
        return this.spine;
    }
    
    public void setSpine(String spine) {
        this.spine = spine;
    }
    
    @Column(name="pns")
    public String getPns() {
        return this.pns;
    }
    
    public void setPns(String pns) {
        this.pns = pns;
    }
    
    @Column(name="skullap")
    public String getSkullap() {
        return this.skullap;
    }
    
    public void setSkullap(String skullap) {
        this.skullap = skullap;
    }
    
    @Column(name="mastoids")
    public String getMastoids() {
        return this.mastoids;
    }
    
    public void setMastoids(String mastoids) {
        this.mastoids = mastoids;
    }
    
    @Column(name="date")
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    
    @Column(name="sex", length=10)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    
    @Column(name="refbydr", length=50)
    public String getRefbydr() {
        return this.refbydr;
    }
    
    public void setRefbydr(String refbydr) {
        this.refbydr = refbydr;
    }




}


