package com.model.reunitdispensedose.dto;
// Generated 22 Aug, 2017 12:51:32 PM by Hibernate Tools 3.2.1.GA


import com.model.medicine.dto.Medicine;
import com.model.redispense.dto.Redispense;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Reunitdispensedose generated by hbm2java
 */
@Entity
@Table(name="reunitdispensedose"
    ,schema="public"
)
@SequenceGenerator(name = "reunitdispensedose_seq", sequenceName = "reunitdispensedose_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Reunitdispensedose  implements java.io.Serializable {


     private long id;
     private Medicine medicine;
     private Redispense redispense;
     private Long quantity;
     private BigDecimal amount;

    public Reunitdispensedose() {
    }

	
    public Reunitdispensedose(long id, Medicine medicine, Redispense redispense) {
        this.id = id;
        this.medicine = medicine;
        this.redispense = redispense;
    }
    public Reunitdispensedose(long id, Medicine medicine, Redispense redispense, Long quantity, BigDecimal amount) {
       this.id = id;
       this.medicine = medicine;
       this.redispense = redispense;
       this.quantity = quantity;
       this.amount = amount;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    @GeneratedValue(generator = "reunitdispensedose_seq")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="medicineid", nullable=false)
    public Medicine getMedicine() {
        return this.medicine;
    }
    
    public void setMedicine(Medicine medicine) {
        this.medicine = medicine;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="redispenseid", nullable=false)
    public Redispense getRedispense() {
        return this.redispense;
    }
    
    public void setRedispense(Redispense redispense) {
        this.redispense = redispense;
    }
    
    @Column(name="quantity")
    public Long getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }
    
    @Column(name="amount", precision=20)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }




}


