package com.model.inbill.dto;
// Generated Mar 29, 2013 6:57:29 PM by Hibernate Tools 3.2.1.GA


import com.model.inVisit.dto.Invisit;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inbill generated by hbm2java
 */
@Entity
@Table(name="inbill"
    ,schema="public"
)

 @SequenceGenerator(name = "inbill_seq", sequenceName = "inbill_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
@SuppressWarnings("serial")
public class Inbill  implements java.io.Serializable {


     private long id;
     private Invisit invisit;
     private BigDecimal consultationcharges;
     private Date createddate;

    public Inbill() {
    }

    public Inbill(long id, Invisit invisit, BigDecimal consultationcharges, Date createddate) {
       this.id = id;
       this.invisit = invisit;
       this.consultationcharges = consultationcharges;
       this.createddate = createddate;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
      @GeneratedValue(generator = "inbill_seq")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="invisitid", nullable=false)
    public Invisit getInvisit() {
        return this.invisit;
    }
    
    public void setInvisit(Invisit invisit) {
        this.invisit = invisit;
    }
    
    @Column(name="consultationcharges", nullable=false, precision=20)
    public BigDecimal getConsultationcharges() {
        return this.consultationcharges;
    }
    
    public void setConsultationcharges(BigDecimal consultationcharges) {
        this.consultationcharges = consultationcharges;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate", nullable=false, length=29)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }




}


