package com.model.detailsOperationBill.dto;
// Generated 10 Sep, 2017 4:40:47 PM by Hibernate Tools 3.2.1.GA


import com.model.operationBill.dto.Operationbillchild;
import com.model.operationType.dto.Operationtype;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detailsoperationbillchild generated by hbm2java
 */
@Entity
@Table(name="detailsoperationbillchild"
    ,schema="public"
)
        @SequenceGenerator(name = "detailsoperationbillchild_seq", sequenceName = "detailsoperationbillchild_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Detailsoperationbillchild  implements java.io.Serializable {


     private long detailsoperationbillidchild;
     private Operationbillchild operationbillchild;
     private Operationtype operationtype;
     private Date detailsoperationbilldatechild;
     private BigDecimal detailsoperationbillchargeschild;

    public Detailsoperationbillchild() {
    }

	
    public Detailsoperationbillchild(long detailsoperationbillidchild, Operationbillchild operationbillchild, Operationtype operationtype) {
        this.detailsoperationbillidchild = detailsoperationbillidchild;
        this.operationbillchild = operationbillchild;
        this.operationtype = operationtype;
    }
    public Detailsoperationbillchild(long detailsoperationbillidchild, Operationbillchild operationbillchild, Operationtype operationtype, Date detailsoperationbilldatechild, BigDecimal detailsoperationbillchargeschild) {
       this.detailsoperationbillidchild = detailsoperationbillidchild;
       this.operationbillchild = operationbillchild;
       this.operationtype = operationtype;
       this.detailsoperationbilldatechild = detailsoperationbilldatechild;
       this.detailsoperationbillchargeschild = detailsoperationbillchargeschild;
    }
   
     @Id 
    
    @Column(name="detailsoperationbillidchild", unique=true, nullable=false)
     @GeneratedValue(generator = "detailsoperationbillchild_seq")
    public long getDetailsoperationbillidchild() {
        return this.detailsoperationbillidchild;
    }
    
    public void setDetailsoperationbillidchild(long detailsoperationbillidchild) {
        this.detailsoperationbillidchild = detailsoperationbillidchild;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="operationbillidchild", nullable=false)
    public Operationbillchild getOperationbillchild() {
        return this.operationbillchild;
    }
    
    public void setOperationbillchild(Operationbillchild operationbillchild) {
        this.operationbillchild = operationbillchild;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="operationtypeid", nullable=false)
    public Operationtype getOperationtype() {
        return this.operationtype;
    }
    
    public void setOperationtype(Operationtype operationtype) {
        this.operationtype = operationtype;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="detailsoperationbilldatechild", length=13)
    public Date getDetailsoperationbilldatechild() {
        return this.detailsoperationbilldatechild;
    }
    
    public void setDetailsoperationbilldatechild(Date detailsoperationbilldatechild) {
        this.detailsoperationbilldatechild = detailsoperationbilldatechild;
    }
    
    @Column(name="detailsoperationbillchargeschild", precision=20)
    public BigDecimal getDetailsoperationbillchargeschild() {
        return this.detailsoperationbillchargeschild;
    }
    
    public void setDetailsoperationbillchargeschild(BigDecimal detailsoperationbillchargeschild) {
        this.detailsoperationbillchargeschild = detailsoperationbillchargeschild;
    }




}


