package com.model.detailsOperationBill.dto;
// Generated 15 Aug, 2017 1:18:40 PM by Hibernate Tools 3.2.1.GA


import com.model.operationBill.dto.Operationbill;
import com.model.operationType.dto.Operationtype;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detailsoperationbill generated by hbm2java
 */
@Entity
@Table(name="detailsoperationbill"
    ,schema="public"
) @SequenceGenerator(name = "detailsoperationbill_seq", sequenceName = "detailsoperationbill_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Detailsoperationbill  implements java.io.Serializable {


     private long detailsoperationbillid;
     private Operationbill operationbill;
     private Operationtype operationtype;
     private Date detailsoperationbilldate;
     private BigDecimal detailsoperationbillcharges;

    public Detailsoperationbill() {
    }


    public Detailsoperationbill(long detailsoperationbillid, Operationbill operationbill, Operationtype operationtype) {
        this.detailsoperationbillid = detailsoperationbillid;
        this.operationbill = operationbill;
        this.operationtype = operationtype;
    }
    public Detailsoperationbill(long detailsoperationbillid, Operationbill operationbill, Operationtype operationtype, Date detailsoperationbilldate, BigDecimal detailsoperationbillcharges) {
       this.detailsoperationbillid = detailsoperationbillid;
       this.operationbill = operationbill;
       this.operationtype = operationtype;
       this.detailsoperationbilldate = detailsoperationbilldate;
       this.detailsoperationbillcharges = detailsoperationbillcharges;
    }

     @Id

    @Column(name="detailsoperationbillid", unique=true, nullable=false)
       @GeneratedValue(generator = "detailsoperationbill_seq")
    public long getDetailsoperationbillid() {
        return this.detailsoperationbillid;
    }

    public void setDetailsoperationbillid(long detailsoperationbillid) {
        this.detailsoperationbillid = detailsoperationbillid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="operationbillid", nullable=false)
    public Operationbill getOperationbill() {
        return this.operationbill;
    }

    public void setOperationbill(Operationbill operationbill) {
        this.operationbill = operationbill;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="operationtypeid", nullable=false)
    public Operationtype getOperationtype() {
        return this.operationtype;
    }

    public void setOperationtype(Operationtype operationtype) {
        this.operationtype = operationtype;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="detailsoperationbilldate", length=13)
    public Date getDetailsoperationbilldate() {
        return this.detailsoperationbilldate;
    }

    public void setDetailsoperationbilldate(Date detailsoperationbilldate) {
        this.detailsoperationbilldate = detailsoperationbilldate;
    }

    @Column(name="detailsoperationbillcharges", precision=20)
    public BigDecimal getDetailsoperationbillcharges() {
        return this.detailsoperationbillcharges;
    }

    public void setDetailsoperationbillcharges(BigDecimal detailsoperationbillcharges) {
        this.detailsoperationbillcharges = detailsoperationbillcharges;
    }




}


