package com.model.user.dto;
// Generated Jun 15, 2016 3:04:42 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,schema="public"
)
         @SequenceGenerator(name = "user_seq", sequenceName = "user_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class User  implements java.io.Serializable {


     private long id;
     private String loginname;
     private String password;
     private String type;
     private Date createddate;

    public User() {
    }

    public User(long id, String loginname, String password, String type, Date createddate) {
       this.id = id;
       this.loginname = loginname;
       this.password = password;
       this.type = type;
       this.createddate = createddate;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
     @GeneratedValue(generator = "user_seq")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="loginname", nullable=false, length=50)
    public String getLoginname() {
        return this.loginname;
    }
    
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }
    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="type", nullable=false, length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="createddate", nullable=false, length=13)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }




}


