package com.model.routineureal.dto;
// Generated Jul 17, 2017 1:15:51 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Routineurine generated by hbm2java
 */
@Entity
@Table(name="routineurine"
    ,schema="public"
)@SequenceGenerator(name = "routineurine_seq", sequenceName = "routineurine_seq")
@org.hibernate.annotations.Entity(dynamicUpdate = true)
public class Routineurine  implements java.io.Serializable {


     private long id;

     private String name;
     private String referredby;
      private String ddate;
     private String namesample;
      private String timeofcollection;



     private String quantity;
     private String appearance;
    
     private String specificgravity;
     private String albumin;
     private String sugar;
     private String bilesalt;
     private String biltpigment;
     private String puscells;
     private String epithelialcells;
     private String casts;
     private String crystals;
     private String rbc;
     private String others;
     private String pragnency;
     private String occultblood;
     private String ovacyst;
     private String rbs;
     private String puscells1;
     private String afb;
     

    public Routineurine() {
    }

	
    public Routineurine(long id) {
        this.id = id;
    }
    public Routineurine(long id, String name, String referredby, String namesample, String timeofcollection, String ddate,String quantity, String appearance, String specificgravity, String albumin, String sugar, String bilesalt, String biltpigment, String puscells, String epithelialcells, String casts, String crystals, String rbc, String others, String pragnency, String occultblood, String ovacyst, String rbs, String puscells1, String afb) {
       this.id = id;

       this.name = name;
       this.referredby = referredby;
       this.ddate = ddate;
       this.namesample = namesample;
       this.timeofcollection = timeofcollection;

       this.quantity = quantity;
       this.appearance = appearance;
       
       this.specificgravity = specificgravity;
       this.albumin = albumin;
       this.sugar = sugar;
       this.bilesalt = bilesalt;
       this.biltpigment = biltpigment;
       this.puscells = puscells;
       this.epithelialcells = epithelialcells;
       this.casts = casts;
       this.crystals = crystals;
       this.rbc = rbc;
       this.others = others;
       this.pragnency = pragnency;
       this.occultblood = occultblood;
       this.ovacyst = ovacyst;
       this.rbs = rbs;
       this.puscells1 = puscells1;
       this.afb = afb;
       
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
      @GeneratedValue(generator = "routineurine_seq")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Column(name="name", length=150)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name="namesample", length=150)
    public String getNamesample() {
        return this.namesample;
    }

    public void setNamesample(String namesample) {
        this.namesample = namesample;
    }

     @Column(name="referredby", length=150)
    public String getReferredby() {
        return this.referredby;
    }

    public void setReferredby(String referredby) {
        this.referredby = referredby;
    }

    @Column(name="ddate")
    public String getDdate() {
        return this.ddate;
    }

    public void setDdate(String ddate) {
        this.ddate = ddate;
    }

     @Column(name="timeofcollection")
    public String getTimeofcollection() {
        return this.timeofcollection;
    }

    public void setTimeofcollection(String timeofcollection) {
        this.timeofcollection = timeofcollection;
    }
    
    @Column(name="quantity")
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    
    @Column(name="appearance")
    public String getAppearance() {
        return this.appearance;
    }
    
    public void setAppearance(String appearance) {
        this.appearance = appearance;
    }
    
    
    
    @Column(name="specificgravity")
    public String getSpecificgravity() {
        return this.specificgravity;
    }
    
    public void setSpecificgravity(String specificgravity) {
        this.specificgravity = specificgravity;
    }
    
    @Column(name="albumin")
    public String getAlbumin() {
        return this.albumin;
    }
    
    public void setAlbumin(String albumin) {
        this.albumin = albumin;
    }
    
    @Column(name="sugar")
    public String getSugar() {
        return this.sugar;
    }
    
    public void setSugar(String sugar) {
        this.sugar = sugar;
    }
    
    @Column(name="bilesalt")
    public String getBilesalt() {
        return this.bilesalt;
    }
    
    public void setBilesalt(String bilesalt) {
        this.bilesalt = bilesalt;
    }
    
    @Column(name="biltpigment")
    public String getBiltpigment() {
        return this.biltpigment;
    }
    
    public void setBiltpigment(String biltpigment) {
        this.biltpigment = biltpigment;
    }
    
    @Column(name="puscells")
    public String getPuscells() {
        return this.puscells;
    }
    
    public void setPuscells(String puscells) {
        this.puscells = puscells;
    }
    
    @Column(name="epithelialcells")
    public String getEpithelialcells() {
        return this.epithelialcells;
    }
    
    public void setEpithelialcells(String epithelialcells) {
        this.epithelialcells = epithelialcells;
    }
    
    @Column(name="casts")
    public String getCasts() {
        return this.casts;
    }
    
    public void setCasts(String casts) {
        this.casts = casts;
    }
    
    @Column(name="crystals")
    public String getCrystals() {
        return this.crystals;
    }
    
    public void setCrystals(String crystals) {
        this.crystals = crystals;
    }
    
    @Column(name="rbc")
    public String getRbc() {
        return this.rbc;
    }
    
    public void setRbc(String rbc) {
        this.rbc = rbc;
    }
    
    @Column(name="others")
    public String getOthers() {
        return this.others;
    }
    
    public void setOthers(String others) {
        this.others = others;
    }
    
    @Column(name="pragnency")
    public String getPragnency() {
        return this.pragnency;
    }
    
    public void setPragnency(String pragnency) {
        this.pragnency = pragnency;
    }
    
    @Column(name="occultblood")
    public String getOccultblood() {
        return this.occultblood;
    }
    
    public void setOccultblood(String occultblood) {
        this.occultblood = occultblood;
    }
    
    @Column(name="ovacyst")
    public String getOvacyst() {
        return this.ovacyst;
    }
    
    public void setOvacyst(String ovacyst) {
        this.ovacyst = ovacyst;
    }
    
    @Column(name="rbs")
    public String getRbs() {
        return this.rbs;
    }
    
    public void setRbs(String rbs) {
        this.rbs = rbs;
    }
    
    @Column(name="puscells1")
    public String getPuscells1() {
        return this.puscells1;
    }
    
    public void setPuscells1(String puscells1) {
        this.puscells1 = puscells1;
    }
    
    @Column(name="afb")
    public String getAfb() {
        return this.afb;
    }
    
    public void setAfb(String afb) {
        this.afb = afb;
    }
    
}


