package com.model.investigation.dto;
// Generated Aug 1, 2014 5:51:48 PM by Hibernate Tools 3.2.1.GA


import com.model.detailInvestigationBill.dto.Detailsinvestigationbill;
import com.model.investigationbill.dto.Investigationbill;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Investigation generated by hbm2java
 */
@Entity
@Table(name="investigation"
    ,schema="public"
)
@SequenceGenerator(name = "investigation_seq", sequenceName = "investigation_seq")
@org.hibernate.annotations.Entity(dynamicUpdate=true)
public class Investigation  implements java.io.Serializable {


     private long investigationid;
     private String investigationtype;
     private BigDecimal investigationcharge;
     private boolean usefull;
     private Set<Investigationbill> investigationbills = new HashSet<Investigationbill>(0);
     private Set<Detailsinvestigationbill> detailsinvestigationbills = new HashSet<Detailsinvestigationbill>(0);

    public Investigation() {
    }

	
    public Investigation(long investigationid, String investigationtype) {
        this.investigationid = investigationid;
        this.investigationtype = investigationtype;
    }
    public Investigation(long investigationid, String investigationtype, BigDecimal investigationcharge, Set<Investigationbill> investigationbills, Set<Detailsinvestigationbill> detailsinvestigationbills) {
       this.investigationid = investigationid;
       this.investigationtype = investigationtype;
       this.investigationcharge = investigationcharge;
       this.investigationbills = investigationbills;
       this.detailsinvestigationbills = detailsinvestigationbills;
    }
   
     @Id 
    
    @Column(name="investigationid", unique=true, nullable=false)
     @GeneratedValue(generator = "investigation_seq")
    public long getInvestigationid() {
        return this.investigationid;
    }
    
    public void setInvestigationid(long investigationid) {
        this.investigationid = investigationid;
    }
    
    @Column(name="investigationtype", nullable=false, length=1000)
    public String getInvestigationtype() {
        return this.investigationtype;
    }
    
    public void setInvestigationtype(String investigationtype) {
        this.investigationtype = investigationtype;
    }
    
    @Column(name="investigationcharge", precision=20)
    public BigDecimal getInvestigationcharge() {
        return this.investigationcharge;
    }
    
    public void setInvestigationcharge(BigDecimal investigationcharge) {
        this.investigationcharge = investigationcharge;
    }


    @Column(name="usefull", nullable=false)
    public boolean isUsefull() {
        return this.usefull;
    }

    public void setUsefull(boolean usefull) {
        this.usefull = usefull;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="investigation")
    public Set<Investigationbill> getInvestigationbills() {
        return this.investigationbills;
    }

    public void setInvestigationbills(Set<Investigationbill> investigationbills) {
        this.investigationbills = investigationbills;
    }
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="investigation")
    public Set<Detailsinvestigationbill> getDetailsinvestigationbills() {
        return this.detailsinvestigationbills;
    }

    public void setDetailsinvestigationbills(Set<Detailsinvestigationbill> detailsinvestigationbills) {
        this.detailsinvestigationbills = detailsinvestigationbills;
    }





}


